.env.development
.env.test
app/controllers/searches_controller.rb
app/models/search.rb
app/views/searches/_form.html.haml
app/views/searches/_results.html.haml
config/locales/en/searches.yml
lib/court_data_adaptor.rb
lib/court_data_adaptor/prosecution_case.rb
lib/court_data_adaptor/query/base.rb
lib/court_data_adaptor/query/defendant.rb
lib/court_data_adaptor/query/prosecution_case.rb
lib/court_data_adaptor/resource/prosecution_case.rb
lib/court_data_adaptor/resource/queryable.rb
spec/features/search/case_reference_spec.rb
spec/features/search/defendant_spec.rb
spec/lib/court_data_adaptor/query/base_spec.rb
spec/lib/court_data_adaptor/query/defendant_spec.rb
spec/lib/court_data_adaptor/query/prosecution_case_spec.rb
spec/lib/court_data_adaptor/resource/prosecution_case_spec.rb
spec/lib/court_data_adaptor/resource/queryable_spec.rb
spec/models/search_spec.rb
spec/requests/search/case_reference_spec.rb
spec/requests/search/defendant_spec.rb
spec/support/shared_examples_for_court_adaptor.rb
spec/support/webmock.rb

Apply strategy pattern to search along with adaptors/queryers
[CACP-169](https://dsdmoj.atlassian.net/browse/CACP-169)
[CACP-117](https://dsdmoj.atlassian.net/browse/CACP-117)
As the main purpose of the app and with different
kinds of searches needing to be applied in future
iterations this pattern should, hopefully, make
extensibility easier.
Introduce the idea of an adaptor (or "queryor", could rename)
that handles particular kinds of searches against particular
resources/endpoints of the API.

Refactor search to use strategy pattern

---

app/controllers/application_controller.rb
spec/features/errors_spec.rb

Internal errors were not being handled correctly
and falling back to the catchall 404 page.
This explicitly catches unhandled exceptions
and redirects to /500 for production environments

Correct raising of internal errors and spec

---

.env.development
.k8s/dev/deployment.yaml

Adaptor API Versioning has been implemented
see [commit](https://github.com/ministryofjustice/laa-court-data-adaptor/commit/07e751cc694bc83d9b3ac0c77e43173e516a44fc)

Amend adaptor api url

---

app/helpers/application_helper.rb
app/views/searches/_results.html.haml

Prevent nil:Nilclass error and i18n::ArgumentError for nils.
Returned objects from API/adaptor does not have a DoB.

Prevent i18n translation error

---

.circleci/config.yml

only the rspec tests currently produce coverage
results and an extra job for upload seems redundant.

upload coverage to codeclimate as part of rspec tests

---

lib/court_data_adaptor/client.rb
lib/court_data_adaptor/query/defendant.rb
lib/court_data_adaptor/query/prosecution_case.rb
lib/court_data_adaptor/resource/base.rb
lib/court_data_adaptor/resource/queryable.rb
spec/lib/court_data_adaptor/client_spec.rb
spec/lib/court_data_adaptor/query/defendant_spec.rb
spec/lib/court_data_adaptor/query/prosecution_case_spec.rb
spec/lib/court_data_adaptor/resource/queryable_spec.rb
spec/support/shared_examples_for_court_adaptor.rb

Fix unauthorized access on bearer token
This prevents unauthorized errors after token expiry (on master)
[CACP-236](https://dsdmoj.atlassian.net/browse/CACP-236)
adaptor implements a two hour expiry and the client is not currently retrieving a fresh token.
note that `client_credentials` do NOT implement `refresh_token` logic.
Reconnect with a fresh token on submission of a query. the retrieving of new token only occurs if the old one has expired - I believe Faraday::OAuth2 is doing this "magically"

Reconnect with fresh token on query, if required

---

.k8s/production/deployment.yaml

Correct the LAA court data adaptor url for prod environment.
n/a
Deployment of View Court Data to production was failing
Correct the value in deployment.yaml.

Correct LAA court data adaptor prod url

---

lib/court_data_adaptor/resource/defendant.rb
spec/lib/court_data_adaptor/resource/defendant_spec.rb

prevent errors when defendant has no name attributes
defendants can be orgnaisations in Common platform.
until such time, if ever, that the adaptor returns
equivalent details for organisation defendants from
CP we need to handle the possibility that a query
returns a defendant organsiation.

Handle defendants with no name attributes

---

Gemfile
Gemfile.lock
spec/features/search/case_reference_spec.rb
spec/features/search/defendant_by_name_spec.rb
spec/features/search/defendant_by_reference_spec.rb
spec/features/search/filters_spec.rb
spec/features/sign_in_spec.rb
spec/features/users/edit_user_spec.rb
spec/features/users/password_change_spec.rb
spec/features/users/password_reset_spec.rb
spec/features/users/password_unlock_spec.rb
spec/support/capybara.rb
spec/support/vcr.rb

Conduct an accessibility audit of court data
[CACP-119 Review accessibility](https://dsdmoj.atlassian.net/browse/CACP-119)
To deliver an accessible product, to meet legal requirements, but best of all, to make sure all our users can easily use what we build.

[CACP-119] Add axe accessbility test

---

package.json
yarn.lock

Afix kind-of, js dependency, to verion >= 6.0.3
Fixes [CVE-2019-20149](https://github.com/advisories/GHSA-6c8f-qphg-qjgp)

bump kind-of@^6.0.3

---

.rubocop.yml

Enables new 0.81 cops: `Lint/RaiseException`, `Lint/StructNewOverride`
Prevents warning below on running rubocop:
```
The following cops were added to RuboCop, but are not configured. Please set Enabled to either `true` or `false` in your `.rubocop.yml` file:
- Lint/RaiseException (0.81)
- Lint/StructNewOverride (0.81)
For more information: https://docs.rubocop.org/en/latest/versioning/
```

Add rubocop configuration for new cops in 0.81

---

app/helpers/govuk_design_system_helper.rb
spec/helpers/govuk_design_system_helper_spec.rb

Extend govuk_page_title to accept a caption
[CACP-309](https://dsdmoj.atlassian.net/browse/CACP-309)
Provide context to heading to make them clearer.
Extend the exiting method to accept a new arg.

Add caption to page title helper

---

docs/development.md

The README doesn't reflect the change made in [this](https://github.com/ministryofjustice/hmcts-common-platform-mock-api/commit/a44cf0b51af847b643ac7a03e22ea44f4c0d255c#diff-f579cccc964135c7d644c7b2d3b0d3ec) commit. This commit ensures the env vars in the README are updated.
So that the application can be run locally.

Update env vars in README

---

Gemfile
Gemfile.lock

This reverts commit 0d8c68299e3391dc39043dd88fe1177705bb44bd.
fix broken deploy and possible cause of errors in app
[CBO-1277](https://dsdmoj.atlassian.net/browse/CBO-1277)
The dependabot upgrade of sidekiq from 5 to 6 broke
the deployment and other problems have arisen probably due
to the environment not having been refreshed since then
sidekiq 6 requires sidekiq to be started in non-daemonized
mode using a supervisor. this is a separate task and a ticket
has been [written to do this - CBO-1299](https://dsdmoj.atlassian.net/browse/CBO-1299). revert for now.
revert the sidekiq major version bump

Revert "Bump sidekiq from 5.2.8 to 6.0.7"

---

app/controllers/defendants_controller.rb
app/views/laa_references/_unlink.html.haml
config/routes.rb
lib/court_data_adaptor/resource/defendant.rb
spec/features/unlinking_a_case_from_maat_spec.rb
spec/lib/court_data_adaptor/resource/defendant_spec.rb
spec/requests/linking/link_laa_reference_spec.rb

We can mark a particular case as "linked" to a MAAT ID, so that it'll get more information from HMCTS' Common Platform.
Sometimes, we'll do this accidentally, or get the wrong ID (since it's free-typed) - this change allows users to reverse the process.
The ["Unlink a case"](https://dsdmoj.atlassian.net/browse/CACP-128) ticket on JIRA.
Questions I have:
- Is it good to merge this and worry about getting the right data across in a follow-up?
- Does [removing this relation](https://github.com/ministryofjustice/laa-court-data-ui/pull/163/files#diff-0c312595236dd3d6c044a0a6a5c6a832L6) have any unintended side effects?

Unlink a case from MAAT 

---

.codeclimate.yml
.rubocop.yml
app/models/feedback.rb
spec/features/breadcrumbs_spec.rb
spec/features/unlinked_defendant_flow_spec.rb
spec/models/user_spec.rb
spec/support/webmock.rb

Updates inline with rubocop 0.85 opt-ins
To improve code quality: Opt-in to new cops,
fix violations and bump codeclimate inline
with this.
- Opt-in to cops from 0.83 to 0.85
- Fix rubocop violations for opt-ins upto version 0.85
- bump codeclimate rubocop 0.76 to 0.83
[latest available rubocop channel](https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop)

Updates inline with rubocop 0.85 opt-ins

---

docs/development.md

Tweak readme to update adaptor url for local running
N/A
Local development
Update the instructions for setting COURT_DATA_ADAPTOR_API_URL for local running

Tweak readme to update adaptor url for local running

---

.circleci/deploy.sh
.k8s/dev/deployment-worker.yaml
.k8s/production/deployment-worker.yaml
.k8s/scripts/deploy.sh
.k8s/staging/deployment-worker.yaml
docker/docker-entrypoint.sh
lib/tasks/worker.rake

create separate pods for workers
N/A
Offloads work to dedicated instances/pods
and works around the sidekiq 6 need for
a supervisor for running sidekiq daemonized,
as we currently do, which will enabled us
to upgrade sidekiq.
Also means we have dedicated sidekiq logs
to look at.

Move sidekiq to worker pods

---

.k8s/staging/deployment-worker.yaml

fixes:
```
error: error parsing .k8s/staging/deployment-worker.yaml: error converting YAML to JSON: yaml: line 40: mapping values are not allowed in this context
error: no objects passed to apply
```

Fix yaml error in staging worker deployment

---

app/controllers/laa_references_controller.rb
app/views/laa_references/_form.html.haml
config/locales/en/views/laa_references.yml
spec/features/linking_defendant_no_maat_id_spec.rb
spec/fixtures/vcr_cassettes/spec/requests/linking/link_defendant_no_maat_id_spec.yml
spec/requests/linking/link_defendant_no_maat_id_spec.rb

Enable linking of defendants with no MAAT id
https://dsdmoj.atlassian.net/browse/CBO-1269
Sometimes a defendant will not have a MAAT id
As per design docs, added  "The MAAT id is missing" govuk_details section to the show defendant view form. Added "Create link without MAAT id" button to this section. Updated laa_references so that when a user clicks the "Create link without MAAT id" button it removes maat_reference from the call to the Court Data Adaptor laa_reference api endpoint.

Cbo 1269 no maat id link

---

.k8s/dev/deployment-worker.yaml
.k8s/dev/deployment.yaml
.k8s/dev/ingress.yaml
.k8s/production/deployment-worker.yaml
.k8s/production/deployment.yaml
.k8s/production/ingress.yaml
.k8s/staging/deployment-worker.yaml
.k8s/staging/deployment.yaml
.k8s/staging/ingress.yaml

Remove Deprecated APIs for Kubernetes version 1.16. See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/apiversion-changes-k8s-1-16.html#removing-deprecated-apis-for-kubernetes-version-1-16
https://dsdmoj.atlassian.net/browse/CBO-1345
To allow for upgrade to Kubernetes v1.16
Amended apiVersion to apps/v1 in deployment.yaml and deployment-worker.yaml
Amended apiVersion to networking.k8s.io/v1beta1 in ingress.yaml

Cbo 1310 fix kubernetes api deprecations

---

.circleci/config.yml

amend env var used to split tests
This was setting and using a different var but
did not matter since it fallsback to all tests,
and we are only running with parrellism of 1
at the moment in any event

Fix testfile var reference for circle test splitting

---

Gemfile
Gemfile.lock

Bump sidekiq to version 6+
Although not directly related to security,
using sidekiq 5 means we cannot bump rack
to (< 2.1) and rack has a vulnerability
that needs handling:
https://github.com/ministryofjustice/laa-court-data-ui/network/alert/Gemfile.lock/rack/open
Since we recently offloaded sidekiq server to worker
pods the previous issue with sidekiq upgrade (proper
daemonization) should no longer be an issue

[security] bump sidekiq 5.2.7 --> 6.10

---

.rubocop.yml

remove warnings for new performance cops in latest version by enabling - rubocop passes

Enable new performance rubocop cops

---

app/controllers/laa_references_controller.rb

Remove duplicated defendant_asn_or_nino parameter from link_attempt permitted parameters
n/a
Added in error
Remove duplicated parameter

Remove duplicated defendant_asn_or_nino_parameter

---

.k8s/scripts/build.sh

previous method broke for local build and push to ECR.
This may require updating of the circleci build and push too
but seems to be working so far (possibly beicase the cp tools
contains an older verion of th cli)

Use aws cli version 2+ command for docker login

---

package.json
yarn.lock

Bump dot-prop to 5.1.1+
Github security alert "Prototype pollution vulnerability in dot-prop npm package version 5.1.0 and earlier allows an attacker to add arbitrary properties to JavaScript language constructs such as objects."

[Security] Bump dot-prop from 4.1.1 to 5.2.0

---

app/controllers/defendants_controller.rb
app/controllers/laa_references_controller.rb
spec/requests/linking/link_defendant_maat_reference_spec.rb
spec/requests/linking/link_defendant_no_maat_id_spec.rb
spec/requests/linking/unlink_defendant_maat_reference_spec.rb

Link and unlinking failure should render not redirect
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=222&projectKey=CBO&modal=detail&selectedIssue=CBO-1415
When View Court Data receives an error on attempting to link or unlink, it should render the current page and display an error, rather than redirect to the current page.
Amended laa_references_controller.rb and defendants_controller.rb create and edit actions respectively.

Cbo 1415 no redirect after linking unlinking

---

package.json
yarn.lock

- Bump http-proxy from 1.17.0 to 1.18.1
- Bump serialize-javascript from 2.1.2 to 3.1.0
Both Github and Yarn dependency alerts identified high severity issues with the above packages.

[Security] Bump http-proxy and serialize-javascript

---

app/controllers/laa_references_controller.rb

Add dependency to controller
Not having this is causing on pod start up
```
Unable to load application: NameError: uninitialized constant CourtDataAdaptor::Errors
Did you mean?  Errno
bundler: failed to load command: puma (/usr/local/bundle/bin/puma)
NameError: uninitialized constant CourtDataAdaptor::Errors
Did you mean?  Errno
```

Add dependency to controller

---

.k8s/dev/ingress.yaml
.k8s/production/ingress.yaml
.k8s/staging/ingress.yaml
.k8s/uat/ingress.yaml

WARNING: resources/ingress.tf required for namespace first
Add ingress class annotations to k8s config #257
[CBO-1455](https://dsdmoj.atlassian.net/browse/CBO-1455)
required by cloud platforms
> We're switching from one big nginx ingress to
having separate ingress controllers for each namespace.
You will need to add a one-line annotation to your ingress
definitions, but not until we ask you to do so. All traffic
to services on the cloud platform goes through ingress
controllers. Over-simplified, this is an AWS load-balancer
plus an nginx webserver, configured to route web traffic to
your service (generally based on the hostname of the web request).
> We originally decided to use a single* ingress controller for all
namespaces. i.e. one AWS load-balancer, and one nginx with a config
block …

Add ingress class annotations to k8s config

---

app/controllers/hearings_controller.rb
app/views/hearings/show.html.haml
app/views/prosecution_cases/show.html.haml
config/locales/en/generic.yml
config/locales/en/views/hearings.yml
spec/requests/hearings_spec.rb

Provide more informative/useful response to users when
hearing details are absent or partially missing.
Currently lack of hearing details will raise
500s which is not very useful or resilient.

Prevent 500s due to lack of hearing details

---

config/webpacker.yml
package.json

Resolve webpacker warnings
Application warnings relating to webpacker (1) Unmet peer dependency, (2) The resolved_paths option has been deprecated

Resolve webpacker warnings

---

app/controllers/pages_controller.rb
app/views/layouts/_footer.html.haml
app/views/pages/contact_us.html.haml
config/locales/en/views/contact_us.yml
config/locales/en/views/layouts.yml
config/routes.rb
spec/features/page/contact_us_spec.rb

Add a 'Contact us' page.
Removal of unused footer links.
Display information on how users can submit general queries pertaining to the web application.

Add contact_us view

---

package.json
yarn.lock

Bump node-forge from 0.9.0 to 0.10.0
High severity security issue with dependency lower than version 0.10.0

[Security] Bump node-forge from 0.9.0 to 0.10.0

---

.k8s/dev/ingress.yaml
.k8s/production/ingress.yaml
.k8s/staging/ingress.yaml
.k8s/uat/ingress.yaml

Revert ingress annotations
> In response to this morning's incident, we are moving
services' ingresses back to the default ingress controller
(we'll publish full details of why this is necessary in our
post-incident report).
> If you have a dedicated ingress controller (i.e. you have a
custom kubernetes.io/ingress.class annotation), please remove this
annotation from your ingress definitions before redeploying your service.
> If you redeploy your service and change back to your dedicated ingress
controller, after we have moved your ingress to the default ingress
controller, your service will be unavailable.

Revert ingress annotations

---

spec/lib/court_data_adaptor/resource/hearing_event_spec.rb

Add hearing event tests to cover properties
as other PR is for providers.
Increase test coverage of this object

Extend hearing_events tests to cover properties

---

app/helpers/application_helper.rb
app/helpers/govuk_design_system_helper.rb
spec/support/capybara_extensions.rb

Fix ruby 2.7 deprecations
Ruby 2.7 deprecated use of last argument as keyword parameters.
This fixes all that occur duing test suite run currently.
```
laa-court-data-ui/app/helpers/application_helper.rb:11:
warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```

Fix ruby 2.7 deprecations

---

README.md

Add badge for codescene project analysis
display link to various metrics on code health and team
dynamics.

Add badge for codescene project analysis

---

app/views/defendants/_offences.html.haml
lib/court_data_adaptor/resource/defendant.rb
lib/court_data_adaptor/resource/offence.rb
spec/features/unlinked_defendant_flow_spec.rb
spec/fixtures/stubs/unlinked_defendant.json
spec/lib/court_data_adaptor/resource/offence_spec.rb
spec/views/defendants/_offences.html.haml_spec.rb

Display plea, plea date, and offence mode of trial to defendant view
[mode of trial reason CBO-1575](https://dsdmoj.atlassian.net/browse/CBO-1575)
[plea details CBO-1588](https://dsdmoj.atlassian.net/browse/CBO-1588)
The mode of trial reason and plea details are required information
for caseworkers as it impacts claimable fee values.
Use amended defedendant endpoint to retrieve these details
see [related PR](https://github.com/ministryofjustice/laa-court-data-adaptor/pull/325)
upon which this functionality depends. However, this could be merged prior
to the adaptor changes without breaking current functionality.

Display plea detail and mode of trial reason for defendant

---

.k8s/staging/http_status_codes_grafana_dashboard.yaml
.k8s/staging/kubernetes_pods_dashboard.yaml
docs/monitoring.md

Create Grafana dashboard(s) to display application metrics.
https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=222&projectKey=CBO&view=planning&selectedIssue=CBO-1587&issueLimit=100
These dashboards are intended as a starting point or proof of concept for future application monitoring.
.k8s/staging/grafana_dashboard.yaml defines a dashboard that shows the number of different types of http requests received by the application within each namespace. This displays one of the metrics scraped by the Prometheus Exporter gem. It can be viewed here https://grafana.cloud-platform.service.justice.gov.uk/d/VxuKVkoMz/laa-court-data-ui-http-status-codes?var-datasource=Prometheus&var-namespace=laa-court-data-ui-production&var-status=200
.k8s/staging/kubernetes_pods_dashboard.yaml defines a …

Add a basic grafana dashboard

---

.circleci/deploy.sh
.k8s/dev/deployment-worker.yaml
.k8s/production/deployment-worker.yaml
.k8s/scripts/deploy.sh
.k8s/staging/deployment-worker.yaml
.k8s/uat/deployment-worker.yaml

Fix `Prometheus Exporter, failed to send message Address not available - connect(2) for "localhost" port 9394` error in worker pods
N/A
Currently the worker pods are logging the error above, as they are not able to connect to a prometheus_exporter
This pr creates a metrics container on worker pods (in the same way as the pods running the application have a metrics container) and runs bundle exec prometheus_exporter in this container. This means that the error above isn't raised and also potentially that we can gather metrics on the worker pods.

Add metrics container to worker pods

---

app/decorators/base_decorator.rb
app/decorators/offence_decorator.rb
app/helpers/application_helper.rb
app/views/defendants/_offences.html.haml
config/environments/development.rb
config/environments/test.rb
config/initializers/court_data_adaptor.rb
config/locales/en/decorators/offence.yml
config/spring.rb
lib/court_data_adaptor/caster/struct_collection.rb
lib/court_data_adaptor/resource/offence.rb
spec/decorators/base_decorator_spec.rb
spec/decorators/offence_decorator_spec.rb
spec/fixtures/i18n/mock.yml
spec/fixtures/stubs/unlinked_defendant.json
spec/helpers/application_helper_spec.rb
spec/lib/court_data_adaptor/caster/struct_collection_spec.rb
spec/lib/court_data_adaptor/resource/offence_spec.rb
spec/lib/court_data_adaptor/resource/provider_spec.rb
spec/support/shared_examples_for_decorators.rb
spec/views/defendants/_offences.html.haml_spec.rb

Display multiple pleas per offence on defendant details page
[CBO-1599](https://dsdmoj.atlassian.net/browse/CBO-1599)
depends on:
[CBO-1597](https://dsdmoj.atlassian.net/browse/CBO-1597)
Changes of plea are possible and the adaptor is
to be amended to return an array of hashes, where
each hash represents a plea.
Stub agreed JSON response for offence pleas from the adaptor.
The response is an array of hashes, which is converted
to an array of OpenStruct objects for convenience.
A convenience method plea_list returns an array
of "plea sentences" (e.g. "Guilty on 01/01/2020")
which can then be displayed in the view.
I have added a decorator/presenter pattern to keep  the presentation logic
out of models/resource-objects while keeping views clean. This pattern is simlar
to CCCDs and can be …

Display multiple pleas on an offence

---

.editorconfig

Apply some standard formattting across supported editors
VS Code is supported and sublimetext has a plugin
see https://editorconfig.org/ for list of
editors with built in support or others
that require a plugin.
To apply consistent standards across diffeerent
editors used by developers.
These default settings are the recommended
by the sublimetext plugin and allow for indent
being specified by tab width. editors should
set their tab width to 2 spaces.
https://packagecontrol.io/packages/EditorConfig

Standardise formatting options across supported editors

---

.k8s/dev/prometheus-custom-rules.yaml
.k8s/production/prometheus-custom-rules.yaml
.k8s/staging/prometheus-custom-rules.yaml
.k8s/uat/prometheus-custom-rules.yaml

The nginex-500-error alert is noisy on all environments (especially production). This is an attempt to make it quieter.
N/A
We want the alert to alert us to genuine application issues.
Change the number of 500 statuses required in a 5 minute period to raise the error from >1 to >5. (I have also  tweaked  * 270 in the expression to * 300 as I am assuming this was a typo for 300 seconds/5 minutes?)

Attempt to quiten nginex-500-error alert

---

.env.development
.k8s/staging/deployment.yaml
app/decorators/offence_decorator.rb
app/views/defendants/_offences.html.haml
lib/court_data_adaptor/resource/offence.rb
spec/decorators/offence_decorator_spec.rb
spec/features/unlinked_defendant_flow_spec.rb
spec/fixtures/stubs/unlinked_defendant.json
spec/lib/court_data_adaptor/resource/offence_spec.rb
spec/views/defendants/_offences.html.haml_spec.rb

Display mode of trial reasons
https://dsdmoj.atlassian.net/browse/CBO-1600
(See https://dsdmoj.atlassian.net/browse/LASB-443 for the related CDA changes)
CDA is returning a new collection, mode_of_trial_reasons. Although in reality we only expect there to be one one mode of trial reason per offence, the structure of hmcts data allows for multiple mode of trial reasons per offence, potentially spread across multiple hearings. This pr allows for a single or multiple mode of trial reasons to be displayed by VCD dependant on what is returned by CDA.
Added a new property mode_of_trial_reasons to lib/court_data_adaptor/resource/offence.rb with type struct_collection  (and deleted old mode_of_trial_reason property). Followed the pattern introduced by pleas to display this collection by adding it …

Cbo 1600 display mode of trial reasons

---

.circleci/config.yml

Specify version of docker to use
Started receiving this during app container build:
```
[3/4] Linking dependencies...
error An unexpected error occurred: "EPERM: operation not permitted, copyfile '/usr/local/share/.cache/yarn/v6/...blahblahblah".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
```
See this [related discussion](https://discuss.circleci.com/t/docker-build-fails-with-nonsensical-eperm-operation-not-permitted-copyfile/37364)
specify version of remote docker as described here
https://circleci.com/docs/2.0/building-docker-images/#docker-version

Specify version of docker to use

---

app/decorators/offence_decorator.rb
spec/decorators/offence_decorator_spec.rb

Apply mappings for common platform mode of trial reasons
https://dsdmoj.atlassian.net/browse/CBO-1633
So that mode_of_trial_reason is hidden for certain associated codes (see https://docs.google.com/spreadsheets/d/1-gkLXxS7DqEPDf5tdMkc3c6_Rtrq2G5xIH6OMSvNyYY/edit#gid=1021818802) and to allow for possible future mode_of_trial_reason mappings to be defined.
Added MODE_OF_TRIAL_REASON_MAPPINGS, currently this allows for mode_of_trial_reason to be hidden for certain associated codes, however, it can be extended in future to allow mode_of_trial_reasons.description to be mapped to different values as required (e.g. 'Directed' and 'Elected' etc.)

Hide mode_of_trial_reasons with certain codes

---

Gemfile
Gemfile.lock
spec/support/capybara.rb
spec/support/matchers/be_accessible.rb

The package axe-matchers has been moved to axe-core-gems. We need to migrate to the new package and update our assertions.
[Migrate axe-matchers to axe-core-rspec](https://dsdmoj.atlassian.net/browse/CBO-1665)
Because the package axe-matchers has been deprecated.

[CBO-1665] Migrate axe-matchers to axe-core-rspec

---

app/views/prosecution_cases/_cracked_ineffective_trial.html.haml

Fix nil class error. will spec after the fact
but this is a prod issue
sentry errors show this against UAT
```
ActionView::Template::Error ProsecutionCasesController#show
error
undefined method `cracked?' for nil:NilClass
```

Prevent nilclass errors

---

spec/views/prosecution_cases/cracked_ineffective_trial.html.haml_spec.rb

Spec the common situation where a mixture of hearings
with and without a cracked_ineffective_trial relation
exists on a prosecution_case
Common situation which raised errors on UAT. Have not
seen such errors on production as yet, but would expect
them.
The safe navigation operator was previously used to
hotfix this scenario.

Spec successful rendering of cracked ineffective trial partial

---

app/controllers/errors_controller.rb
spec/requests/errors_spec.rb

Handle unexpected formats for not_found responses
Prevent sentry error clutter from requests to non-existent paths/pages
with unhandled formats as well.
Example error:
```
ActionView::MissingTemplate
Missing template errors/not_found, application/not_found with {:locale=>[:en], :formats=>[:text], :variants=>[], :handlers=>[:raw, :erb, :html, :builder, :ruby, :haml]}
```
The missing template error results from the format (e.g. `:formats=>[:text]`)
itself. Such requests appear to be be vulnerability scans. As such they are not
something we need cluttering up sentry - they are recorded
by our prometheus monitoring and alerting setup in any event.
Keep responding to `html` requests with the errors#not_found template
as usual, but all other formats can respond with plain text.

Handle unexpected formats for not_found responses

---

.dependabot/config.yml

Add team devs as default dependabot reviewers
n/a
Any team dev can review and approve dependabot
PR.s this automates the assignment of devs.
Note: we should move to version 2 of the
dependabot githubnative config. see
cccd for example.

Add team devs as default dependabot reviewers

---

Gemfile
Gemfile.lock

Getting build errors as below. bootsnap is
the dependency that use msgpack and it has released
a fix today thankfully.
```
Your bundle is locked to msgpack (1.4.1-java), but that version could not be
found in any of the sources listed in your Gemfile. If you haven't changed
sources, that means the author of msgpack (1.4.1-java) has removed it. You'll
need to update your bundle to a version other than msgpack (1.4.1-java) that
hasn't been removed in order to install.
```
Bootsnap [changelog](https://github.com/Shopify/bootsnap/blob/master/CHANGELOG.md)

Bump bootsnap 1.6.0 --> 1.7.0

---

lib/court_data_adaptor/query/defendant/by_name.rb
spec/lib/court_data_adaptor/query/defendant/by_name_spec.rb

squish names for search to ensure extra whitespace
has no impact
Additional whitespace is being added to the
the name coming from the adaptor, making
comparison fail.
I have [raised an issue with the adaptor](https://github.com/ministryofjustice/laa-court-data-adaptor/issues/395)
and a [fix PR for it](https://github.com/ministryofjustice/laa-court-data-adaptor/pull/397) but we can handle this our side to for assurance.
By removing whitespace from ends and between multiple names
and doing a case insensitive search against the adaptor
results we can remove search failures resulting from whitespace

Change names search to handle extra whitespace

---

app/controllers/prosecution_cases_controller.rb
app/views/prosecution_cases/_cracked_ineffective_trial.html.haml
app/views/prosecution_cases/_defendants.html.haml
app/views/prosecution_cases/_hearing_summaries.html.haml
app/views/prosecution_cases/_raw_response.html.haml
app/views/prosecution_cases/show.html.haml
config/locales/en/generic.yml
spec/views/prosecution_cases/_cracked_ineffective_trial.html.haml_spec.rb
spec/views/prosecution_cases/_hearing_summaries.html.haml_spec.rb
spec/views/prosecution_cases/show.html.haml_spec.rb

Refactor the prosecution case "show" flow
n/a
Removes the need to iterate over an array of
results to retrieve the prosectution_case object.
There can only be one prosecution_case
per URN - we might want to consider raising
an error if there is ever more than one.
This removes a lot of clutter and logic
from the views. It also moves the decoration
of the prosecution_case to the controller so
any views/partials do not need to decorate
individually.
decorate prosecution_case in the prosecution_case_controller
and use this decorated object directly in the views.

Refactor the prosecution case "show" flow

---

app/controllers/hearings_controller.rb
app/views/hearings/_listing_info.html.haml
app/views/hearings/show.html.haml
config/locales/en/generic.yml
spec/features/breadcrumbs_spec.rb
spec/features/unlinked_defendant_flow_spec.rb

Change header and breadcrumb for hearings page to "Hearing day {date}"
[CBO-1417](https://dsdmoj.atlassian.net/browse/CBO-1417)
Designer wants to make it clear to users that they are
only viewing a single hearing days event logs
for the hearing.

Change header for hearings page

---

app/decorators/cracked_ineffective_trial_decorator.rb
spec/decorators/cracked_ineffective_trial_decorator_spec.rb
spec/views/prosecution_cases/_cracked_ineffective_trial.html.haml_spec.rb

Supply hearing day for cracked ineffective trial link
This was missed from previous PR to add the hearing
days for other hearing summary links.
It also styles the link correctly.

Supply hearing day for cracked ineffective trial link

---

spec/features/unlinking_a_defendant_from_maat_spec.rb
spec/requests/defendants_spec.rb
spec/requests/linking/unlink_defendant_maat_reference_spec.rb
spec/support/stub_helper.rb

move the api_url to a spec support helper
Its use in quite a few places

Extract common rspec `let` api_url to a helper

---

spec/support/vcr.rb

specs tagged with :vcr will only
match requests to recordings based on
the path and query of the request, not
the domain.
Allows cassettes recorded against one
adaptor domain (or local) to function
as expected for feature tests, irrespective
of the app configuration which defines which
adaptor domain to make requests to.

Configure vcr hook to match on path and query

---

Gemfile.lock

Update the version of Bundler used to 2.2.11.
N/A
This version of Bundler fixes a recently discovered dependency vulnerability. See [here](https://bundler.io/blog/2021/02/15/a-more-secure-bundler-we-fixed-our-source-priorities.html) for more details.
```bash
gem install bundler
bundle update --bundler
```

Update version of bundler

---

app/helpers/govuk_design_system_helper.rb
app/views/hearings/_pagination.html.haml
app/views/hearings/show.html.haml
spec/helpers/govuk_design_system_helper_spec.rb

Update pagination UI of hearing days
[Update pagination UI of hearing days](https://dsdmoj.atlassian.net/browse/CBO-1728)
The current style adds too much spacing between the heading and the pagination, and too little spacing between the pagination and the next sibling.
This did not meet the design reference.
Updated the `govuk_page_title` helper to accept a third argument that allows us to add custom classes, then, using [spacing overrides](https://design-system.service.gov.uk/styles/spacing/) to update the UI to match the design reference.

[CBO-1728] Update pagination UI of hearing days

---

Gemfile
Gemfile.lock

Remove the `climate_control` gem.
N/A
This gem is no longer, or never was, used.

Remove the climate_control gem

---

package.json
yarn.lock

CVE-2021-27290
high severity
Vulnerable versions: >= 5.2.2, < 8.0.1
Patched version: 8.0.1
ssri 5.2.2-8.0.0, fixed in 8.0.1, processes SRIs using a regular expression which is vulnerable to a denial of service. Malicious SRIs could take an extremely long time to process, leading to denial of service. This issue only affects consumers using the strict option.

[security] selectively bump ssri from 6.0.1 to 8.0.1

---

package.json
yarn.lock

CVE-2021-28092
high severity
Vulnerable versions: >= 2.1.0, < 4.2.2
Patched version: 4.2.2
The is-svg package 2.1.0 through 4.2.1 for Node.js uses a regular expression that is vulnerable to Regular Expression Denial of Service (ReDoS). If an attacker provides a malicious string, is-svg will get stuck processing the input for a very long time.

[security] selectively bump is-svg from 3.0.0 to 4.3.1

---

spec/models/search_spec.rb
spec/support/matchers/have_activemodel_error_message.rb
spec/support/matchers/have_activemodel_error_type.rb
spec/validators/char_length_validator_spec.rb

Spec the validator that was added as
part of partial name search
Was missed/not-added as part of partial name
search implementation
Add spec and a custom rspec matcher
to help with tests. Also rename the
previous have_activerecord_error custom
matcher to better reflects its use and
purpose and remove a redundant use of
it.

Add CharLengthValidator spec

---

app/views/prosecution_cases/_raw_response.html.haml

When viewing a prosecution case where the hearing_events is not present, an error is encountered in the raw json response of the request.
Error is encountered where hearing_events is not present, preventing the page from loading.
Adding checks for where hearing_events is blank in the json before trying to render it.

Add fix for where hearing_events is not present in response

---

app/views/hearings/_hearing_events.html.haml
app/views/hearings/show.html.haml

An error is thrown when viewing a hearing where the hearing_events is not present. Part 2 to [this PR](https://github.com/ministryofjustice/laa-court-data-ui/pull/573), which fixes the case view.
Error is encountered where hearing_events is not present, preventing the page from loading.
Adding check for if hearing_events is present before trying to render it.

Add fix for hearings view where hearing_events is not present in response 

---

app/views/hearings/_hearing_events.html.haml
lib/court_data_adaptor/resource/hearing_event.rb
spec/lib/court_data_adaptor/resource/hearing_event_spec.rb
spec/views/hearings/_hearing_events.html.haml_spec.rb

Change View Court Data so that it can accept the free text field (notes) associated with various events sent from CP. Add small bump of space to indicate change between “hearing event” and “note”
[Implement free text in VCD](https://dsdmoj.atlassian.net/browse/AAC-62)
Court Clerks want to add free text so that they can send extra details related to hearing events. HMCTS has provided a new set of schemas that are intended to support the addition of free text to the hearing event log API. CDA has been modified to accommodate this new information & transmit this data from CPP to VCD.
New Information in relation to hearings will be added as a free text & this information is required for LAA billing caseworkers to evaluate bills effectively. 
- Display the notes field for each hearing event …

[AAC-62] Display event hearing notes

---

app/helpers/hearing_helper.rb
app/views/hearings/_hearing_events.html.haml
app/webpack/stylesheets/application.scss
app/webpack/stylesheets/components/_hearing_events.scss
lib/court_data_adaptor/resource/hearing_event.rb
spec/helpers/hearing_helper_spec.rb
spec/lib/court_data_adaptor/resource/hearing_event_spec.rb
spec/views/hearings/_hearing_events.html.haml_spec.rb

Change View Court Data so that it can display free text field (hearing event notes) associated with various hearing events sent from CP. Hearing event notes will be max 3000 characters. Add small bump of space to indicate change between “hearing event description” and “note”.
A [PR was previously opened](https://github.com/ministryofjustice/laa-court-data-ui/pull/570#issue-643325845) with comments. Two additional commits were made in this PR with changes to:
- Ensure carriage return and new line characters `\n` `\r` are displayed as new line, etc.
- Limit width of table column width to enforce a line break in case of long unbreakable string inputs
[Implement free text in VCD](https://dsdmoj.atlassian.net/browse/AAC-62)
Court Clerks want to add free text so that they can send extra details …

[AAC-54] events free text

---

spec/views/hearings/show.html.haml_spec.rb

Prosecution case page ([raw_response section](https://github.com/ministryofjustice/laa-court-data-ui/pull/573)) and hearings page ([hearing_events](https://github.com/ministryofjustice/laa-court-data-ui/pull/574/files)) were not displaying in VCD on UAT, causing the case page to return an error page when the user tries to view a case. A fix was put in to check that hearing_events is present before trying to render but it was missing tests.  
[Add test for hearing events fix](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=622&projectKey=AAC&selectedIssue=AAC-83)
The fix was made urgently and so it is missing a unit test. 
Test that if hearing_events is not present, the relevant partial will not be rendered.

Test hearing_events template is not rendered if hearing_events is missing

---

app/helpers/application_helper.rb
app/views/layouts/_phase_banner.html.haml
app/views/layouts/application.html.haml
app/webpack/stylesheets/application.scss
app/webpack/stylesheets/components/_phase_banner.scss
spec/features/layout_spec.rb
spec/helpers/application_helper_spec.rb
spec/support/application.rb

We need a banner on the UAT environment
https://dsdmoj.atlassian.net/browse/AAC-79
Some of our users have logged into UAT and reported bugs because they are using test data. We still need caseworkers and other “non-technical” users to be testing new features/data that comes through from Common Platform. A banner would help avoid any users making this mistake and accidentally causing disruption.
Followed the suggestion on the ticket of modifying the Alpha/Beta banner to display the environment with a different colour (NB this is only for the dev, staging and uat environment, all other environments should be as is).

Modify alpha/beta banner to display environment for non-prod envs

---

docs/development.md

Update local CDA setup documentation
[board ticket description](https://dsdmoj.atlassian.net/browse/AAC-91)
Some Postgres setup errors were encountered when setting up CDA locally according to the README.
To avoid possible Postgres errors encountered when trying to run `rails console` to generate OAuth2 credentials, the readme now sets the CDA database URL and creates the database first which will hopefully prevent this for others.

Update local CDA setup documentation

---

app/helpers/govuk_design_system_helper.rb
app/views/hearings/_court_applications.html.haml
spec/helpers/govuk_design_system_helper_spec.rb

Simplified the code and added a helper for the GDS description lists
[AAC-103 Refactor to use helpers to reduce duplication](https://dsdmoj.atlassian.net/browse/AAC-103)
Description lists are common components used several times in the bespoke accordion for court applications.  Using a helper makes maintenance easier and the court applications file considerably shorter
New Ruby helpers for:
- each row in a `<dl>` list
- each key in a row
- each value in a row
The first helper calls the remaining two - which can be called separately if needed on a different page.

AAC-103 Added Ruby helper for GDS description lists

---

package.json
yarn.lock

Selective version resolution of hosted-git-info.
CVE-2021-23362
moderate severity
Vulnerable versions: >= 3.0.0, < 3.0.8
Patched version: 3.0.8
The npm package hosted-git-info before 3.0.8 are vulnerable to Regular Expression Denial of Service (ReDoS) via regular expression shortcutMatch in the fromUrl function in index.js. The affected regular expression exhibits polynomial worst-case time complexity

[Security] Bump hosted-git-info to 3.0.8

---

package.json
yarn.lock

Selective dependency resolutions of normalize-url to v4.5.1
CVE-2021-33502
high severity
Vulnerable versions: < 4.5.1
Patched version: 4.5.1
The normalize-url package before 4.5.1, 5.x before 5.3.1, and 6.x before 6.0.1 for Node.js has a ReDoS (regular expression denial of service) issue because it has exponential performance for data: URLs.

[Security] Selectively bump normalize-url to 4.5.1

---

package.json
yarn.lock

Selective dependency resolutions of glob-parent to v5.1.2
CVE-2020-28469
high severity
Vulnerable versions: < 5.1.2
Patched version: 5.1.2
This affects the package glob-parent before 5.1.2. The enclosure regex used to check for strings ending in enclosure containing path separator.

[Security] Selectively bump glob-parent to 5.1.2

---

package.json
yarn.lock

Selective dependency resolutions of css-what to v5.0.1
[Denial of service in css-what](https://github.com/advisories/GHSA-q8pj-2vqx-8ggc)

[Security] Selectively bump css-what to 5.0.1

---

app/views/errors/internal_error.html.haml
app/views/errors/not_found.html.haml
app/views/errors/unacceptable.html.haml
config/locales/en/views/error.yml
spec/features/errors_spec.rb

Added GDS styling to error pages
Minor changes to wording to reflect wording used on [GDS Design System patterns](https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/)
Adds and updates existing RSpec tests for error page content.
[Change Styling on Error pages to match the GDS pattern](https://dsdmoj.atlassian.net/browse/AAC-146)
Uses set font sizes and typeface as used elsewhere to make these error pages easier to read and in line with the standard.
Apply GDS classes

AAC-146 Error Page Styling

---

app/helpers/govuk_design_system_helper.rb
app/views/layouts/_flashes.html.haml
app/webpack/stylesheets/application.scss
app/webpack/stylesheets/components/_notification_banner.scss
spec/helpers/govuk_design_system_helper_spec.rb

Introduces a notification banner helper and spec tests
[AAC-168 Add Ruby helper for notification banners including a failure option](https://dsdmoj.atlassian.net/browse/AAC-168)

AAC-168 Notification Banner Helper and Spec Tests

---

app/views/layouts/_google_analytics.html.haml

Update the config for GA to allow the siteSpeedSampleRate to be at 100% so that we can understand what page load times our consumers have
[AAC-195](https://dsdmoj.atlassian.net/browse/AAC-195)
Currently GA doesnt show anything for Page load times. This is because as default GA sets this to 1% so our sample rate is too low to understand what is happening. 
Value updated as per https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#siteSpeedSampleRate
Screenshot to show page timings now coming through to GA in Dev.

AAC-199 - Increase GA site sample speed for page load times

---

config/initializers/sentry.rb

[Sentry performance ticket](https://dsdmoj.atlassian.net/browse/AAC-245)
Enable Sentry performance monitoring
- Set the sample rate to 0.5% which is 0.05 for traces_sample_rate

AAC-245 Enable Sentry performance monitoring

---

.k8s/dev/ingress.yaml
.k8s/production/ingress.yaml
.k8s/staging/ingress.yaml
.k8s/uat/ingress.yaml

Add Rogue IP addresses that are path scanning to the deny list on the K8s ingress.
[VCD - Block Rogue IP addresses from Path scanning application](https://dsdmoj.atlassian.net/browse/AAC-262)
To remove the security concern of being path scanned
Using the nginx annotation, i have added the 3 ip addresses to a deny list on the base url of the site which should disallow access to the whole site.

AAC-262 - Add Rogue IP addresses to deny list

---

.k8s/dev/ingress.yaml
.k8s/production/ingress.yaml
.k8s/staging/ingress.yaml
.k8s/uat/ingress.yaml

Update Rogue IP addresses that are path scanning to the deny list on the K8s ingress.
[VCD - Block Rogue IP addresses from Path scanning application](https://dsdmoj.atlassian.net/browse/AAC-262)
To remove the security concern of being path scanned
Using the nginx annotation, i have added the 3 ip addresses to a deny list on the base url of the site which should disallow access to the whole site.

AAC-262 - Add additional scanning ip

---

.k8s/dev/ingress.yaml
.k8s/production/ingress.yaml
.k8s/staging/ingress.yaml
.k8s/uat/ingress.yaml

Block IP addresses that are attempting to hack our service. First noticed in our logs visualizer as they were attempting php attacks
[VCD - Block Rogue IP addresses from Path scanning application](https://dsdmoj.atlassian.net/browse/AAC-262)
This will help secure our system from more attempts on our service.
Add the ip addresses to the ingress deny list configuration.

AAC-262 Add more IP addresses for blocking in ingress file

---

package.json
yarn.lock

Resolve yarn packages security vulnerabilities
N/A
See Github's Advisory database related to issues
nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
set-value - https://github.com/advisories/GHSA-4jqc-8m5r-9rpr
Selectively bump yarn packages `nth-check` and `set-value`

[Security] Selectively bump yarn packages `nth-check` and `set-value`

---

.github/CODEOWNERS

Codeowners is a github functionality. It allows for automatically adding a reviewer to a PR if it changes something they "own" e.g. any PR that changes a javascript file will request a review from the frontend team members etc.
[AAC-188](https://dsdmoj.atlassian.net/browse/AAC-188)
This allows us to abstract away automatic Pull Request reviewers from Dependabot. Aswell as making it known which team member needs to know about changes to which file. This means we can make sure the right people are aware and reviewing changes merged to the app.
Add a CODEOWNERS file and configurate it to alert the whole laa-assess-a-claim team for any changes in the app.

AAC-188 Add a github CODEOWNERS file

---

spec/factories/users.rb

Flashing test in CI complaining of uniqueness validation error on usernames.
The uniqueness validation is triggered because the user factory (`spec/factories/users.rb`) generates usernames using the first 4 letters of the surname and first letter of first name of the user, where random names are generated by the Faker gem. 
There are therefore situations by chance where two users created by FactoryBot have the same username.
Example failure in CI: https://app.circleci.com/pipelines/github/ministryofjustice/laa-court-data-ui/3809/workflows/6d1dce72-93ca-40ff-bc55-834ed498e5bc/jobs/12867/tests#failed-test-0
```
Failure/Error: let(:other_user) { create(:user, roles: ['caseworker']) }
ActiveRecord::RecordInvalid:
Validation failed: Username Username already taken
Shared Example Group: "not …
```

Add integer to factory usernames

---

.k8s/live-1/production/deployment-worker.yaml

Prod workers are not deploying due to a CrashBackoffLoop we saw in pre-prod. This was fixed by using the GEM.
[Upgrade Ruby to version 3 in VCD](https://dsdmoj.atlassian.net/browse/AAC-263)

AAC-263 - Use gem for liveness/readiness checks

---

.circleci/config.yml

The production build is complaining that it cannot find rails. I believe this is due to layer caching in the docker setup in circleci
[Upgrade Ruby to version 3 in VCD](https://dsdmoj.atlassian.net/browse/AAC-263)

AAC-263 - Remove docker layer caching for deploying builds

---

docker/Dockerfile

Due to environmental issues it appears the latest version of the docker image is failing in production
[Upgrade Ruby to version 3 in VCD](https://dsdmoj.atlassian.net/browse/AAC-263)

AAC-263 - Downgrade docker version to 3.13

---

.k8s/live-1/production/ingress.yaml
.k8s/live/production/ingress.yaml

As apart of our EKS migration, we need to do a split of traffic to ensure that everything is working as we expect. 
[Migrate View Court Data Prod onto the Production EKS Implementation](https://dsdmoj.atlassian.net/browse/AAC-393)
Mandatory EKS Migration

AAC-393 - Update ingress to split traffic 50/50

---

.k8s/live-1/production/ingress.yaml
.k8s/live/production/ingress.yaml

What
As apart of our EKS migration, we need to do move the traffic over to the live cluster. 
Ticket
[Migrate View Court Data Prod onto the Production EKS Implementation](https://dsdmoj.atlassian.net/browse/AAC-393)
Why
Mandatory EKS Migration

AAC-393 - Make weighting of traffic 100% to live cluster

---

app/views/cookies/_form.html.haml
app/views/layouts/_cookie_banner.html.haml
cypress.json
cypress/config/develop.json
cypress/config/staging.json
cypress/config/uat.json
cypress/integration/index/cookie_banner.spec.js
cypress/integration/index/cookie_settings.spec.js
cypress/integration/index/cookies.spec.js
cypress/integration/index/sign_in.spec.js
cypress/support/commands.js
package.json
yarn.lock

Add Cypress tests for Cookies (banner and settings page) and more Login/Logout tests
[AAC-162](https://dsdmoj.atlassian.net/browse/AAC-162?atlOrigin=eyJpIjoiNWRjOTdhOTFlYzJkNDQ1ZTllOTc4MmIzZGExNzliYTIiLCJwIjoiaiJ9)
- To test and ensure rigidity of the cookies feature
- To not pollute genuine data in Google Analytics
- Add customised data attributes for cypress testing to meet best practices [here](https://docs.cypress.io/guides/references/best-practices#Selecting-Elements)
- Add cypress tests to accept and reject cookies
- Add cypress tests to adjust cookie settings
- Add cypress testing to check for the change in two cookies: cookies_preferences_set and analytics_cookies_set
- Add cypress tests to test the logout procedure
- Update cypress configuration on all environments to block calls …

AAC-162 Cypress Test Cookies and Login/Logout

---

.k8s/live/dev/deployment-worker.yaml
.k8s/live/dev/deployment.yaml
.k8s/live/production/deployment-worker.yaml
.k8s/live/production/deployment.yaml
.k8s/live/staging/deployment-worker.yaml
.k8s/live/staging/deployment.yaml
.k8s/live/uat/deployment-worker.yaml
.k8s/live/uat/deployment.yaml
Gemfile.lock

Update CDA Urls so that when migration happens we dont error
[Update CDA endpoints to non namespace specific URLS](https://dsdmoj.atlassian.net/browse/AAC-447)
We are using cluster specific URLS and when migration is complete we could be left with out of date URLS

AAC-447 - Update urls for CDA

---

.github/workflows/codeql-analysis.yml
docker/Dockerfile

Fixes  Integer Overflow or Wraparound vulnerability on ruby:3.1.0-alpine3.14
More details on issue can be found [here](https://security.snyk.io/vuln/SNYK-ALPINE314-GMP-2419278)
Upgrade [gmp](https://pkgs.alpinelinux.org/package/edge/main/x86/gmp) via Alpine Package Manager

Upgrade GMP to resolve security vulnerability

---

lib/feature_flag.rb
spec/lib/feature_flag_spec.rb

Add feature flag class to allow us to put future work behind feature flags for speed of development. 
[Add feature flag ability to CD UI](https://dsdmoj.atlassian.net/browse/AAC-547)
Future work is going to require us to iterate on our implementation without a production release. This should allow us to do just that. 
The class will read from the Environment variable the true/false value and return the bool. If it is not the a default false will be returned.

AAC-547 - Add implementation of Feature Flag class

---

app/controllers/application_controller.rb
spec/features/errors_spec.rb

Added additional error checking in the application controller for general Active Resource errors that may occur that we can capture
[Add Application Level ActiveResource Error Handling](https://dsdmoj.atlassian.net/browse/AAC-562)
Add resilience in our API
Capture 403, timeout and server errors at an application level to ensure that we display friendly information at the time of an error. Also log to sentry so we can know things are happening.

AAC-562 - Add additional error handling

---

app/controllers/hearings_controller.rb
app/models/cd_api/hearing_events.rb
app/views/hearings/_hearing_events_v2.html.haml
app/views/hearings/show.html.haml
spec/fixtures/stubs/cd_api/hearing_events_empty_response.json
spec/fixtures/stubs/cd_api/hearing_events_response.json
spec/requests/hearings_spec.rb
spec/support/webmock/court_data_api/webmock.rb
spec/views/hearings/_hearing_events_v2.html.haml_spec.rb

Add Hearing Events to come from V2 if hearing_events env var is enabled. 
[Integrate CDAPI Hearing Events to the Hearing Page events table](https://dsdmoj.atlassian.net/browse/AAC-606)
Migration to V2 for View Court Data
- Create new v2 hearing_events partial as we no longer need a decorator to sort through the prosecution_cases response
- Add model to hit hearing_events endpoint
- Add logic into hearings controller to call hearing_events if V2 enabled
- Add logic in hearing page to show correct table based on V2 flag

AAC-606 - Add hearing events from V2 if flag enabled

---

.k8s/live/production/deployment.yaml

Add LAA_REFERENCES env var to prod and set to true for V2 release of MAAT linking and unlinking
[CDUI - Enable MAAT Linking/ Unlinking in V2](https://dsdmoj.atlassian.net/browse/AAC-584)
V2 Migration

AAC-584 - Update to set env_var to true

---

app/controllers/feedback_controller.rb
app/models/ability.rb
spec/features/feedback_spec.rb
spec/requests/feedback_spec.rb

Put feedback form behind auth to prevent unwanted bot attacks.
[Move Court Data Feedback form behind an authorisation wall](https://dsdmoj.atlassian.net/browse/AAC-625)
Bot attacks focus this form due to its un-authenticated nature.

AAC-625 - Put feedback form behind auth

---

app/controllers/hearings_controller.rb
config/initializers/logstasher.rb
config/locales/en/views/error.yml
config/locales/en/views/hearings.yml
spec/features/hearings_v2_spec.rb
spec/support/webmock/court_data_api/webmock.rb

Adds error handling around the hearing events so that if we receive 400s the page doesnt error and if we receieve 424 or 500s we show a flash
[CD UI - Hearing Events V2 Requires Error Handling](https://dsdmoj.atlassian.net/browse/AAC-631)
To ensure a better user experience within the application
- Ensure 404 is captured and returns nil so that the events table is not rendered.
- Ensure 424 and 500s are captured, sent to sentry and return nil so table is not rendered. Also show flash to indicate there is an issue.

AAC-631 - Add error handling around hearing events

---

.k8s/live/uat/deployment.yaml

Enable Defendant Search to utilise the V2 endpoints on UAT
This effects the Search Results page and the Defendants Page
[CDUI - Enable Case Search Via V2](https://dsdmoj.atlassian.net/browse/AAC-627)
- [Related Dev PR](https://github.com/ministryofjustice/laa-court-data-ui/pull/999)
V2 Migration
`DEFENDANTS_SEARCH: true`

AAC-627 - Enable defendants search on UAT

---

.k8s/live/production/deployment.yaml
.k8s/live/uat/deployment.yaml

Rollback from production and uat for defendants search because of missing plea data in prod
[board ticket description](link)

AAC-627 Rollback defendants search feature for Production and UAT

---

app/controllers/defendants_controller.rb
app/controllers/laa_references_controller.rb
app/views/defendants/_form.html.haml
app/views/laa_references/_form.html.haml
config/database.yml
spec/features/defendants_view_spec.rb
spec/features/unlinking_a_defendant_from_maat_v2_spec.rb
spec/requests/linking/link_defendant_maat_reference_v2_spec.rb
spec/requests/unlinking/unlink_defendant_maat_reference_v2_spec.rb

[Split Feature Flags for Defendant Page and Search page](https://dsdmoj.atlassian.net/browse/AAC-635)
Currently the Search page in the beginning of the user journey of CD UI and the Defendant page after the Prosecution Case page are under one feature flag for v2 (DEFENDANT_SEARCH). This means both have to be ready to release either. 
To allow us to be more flexible and deliver value to users quicker, we should split these flags up into: 
DEFENDANT_SEARCH
DEFENDANT_PAGE
Split defendant feature flags to: 
DEFENDANT_SEARCH
DEFENDANT_PAGE

Split Feature Flags for Defendant Page and Search page

---

.k8s/live/uat/deployment.yaml

[CDUI - Enable defendant search via v2](https://github.com/ministryofjustice/laa-court-data-ui/pull/1010)
Now that the work has been done and implemented to have a feature flag around V1/V2 of the Common Platform Case searching work, we need to enable it in the environments so that it can be tested/used and ensure that it is working as intended and then released for general use (without affecting the defendant page)
Change UAT DEFENDANTS_SEARCH flag in kubernetes deployment config file

Re-enable DEFENDANT_SEARCH flag in UAT

---

.k8s/live/production/deployment.yaml

[CD UI - Enable Defendants Search](https://dsdmoj.atlassian.net/jira/software/c/projects/AAC/boards/622?modal=detail&selectedIssue=AAC-636)
Now that the work has been done and implemented to have a feature flag around V1/V2 of the Common Platform Case searching work, we need to enable it in the environments so that it can be tested/used and ensure that it is working as intended and then released for general use.

Enable DEFENDANTS_SEARCH flag in production

---

.k8s/live/uat/deployment.yaml

Enable HEARING flag on UAT by setting to TRUE in deployment.yaml file
[CDUI - Enable Population of Hearing Day Via V2](https://dsdmoj.atlassian.net/jira/software/c/projects/AAC/boards/622?modal=detail&selectedIssue=AAC-628)
So that we can test UAT to confirm no negative impact to users as we enable v2
--------

Enable HEARING flag on UAT

---

app/models/cd_api/defendant.rb

[Accessing Defendant Page via Search Fails in v2](https://dsdmoj.atlassian.net/jira/software/c/projects/AAC/boards/622?modal=detail&selectedIssue=AAC-656)
Because when accessing defendant page via search page when search page is in v2, opening the page fails as the linked? method is missing
Add linked method to CD API defendant model using the first offence summary

Aac 656 accessing defendant page via search

---

app/views/hearings/_details_v2.haml

Using the `hearing_days` array and using the sittings day property to show the time listed as opposed to the `shared_time`
[Repoint Time Listed on CD UI to Listing Time ](https://dsdmoj.atlassian.net/browse/AAC-683)
Data parity between V1 and V2

AAC-683 - Change the time we are using

---

.circleci/config.yml

Reuse cache for building to increase speed and parrellise the rspec tests to reduce time taken
[Apply Parralelism to R-spec Testing in Circle CI](https://dsdmoj.atlassian.net/browse/AAC-643)
Decrease time to production on code releases
- Reuse cached bundle/yarn
- parrellise rspec
- remove rebuilds in steps
- extra step for codeclimate away from push

AAC-643 - Build speed increases and parrellism

---

.k8s/live/staging/deployment.yaml

Enable v2 Flag for Hearing page on STAGING environment
[CDUI - Enable Population of Hearing Day Via V2](https://dsdmoj.atlassian.net/browse/AAC-628)
To test v2 upgrade of VCD in Staging Environment - upgrade will lead to performance increase for users on VCD
Update Kubernetes deployment.yaml file for staging env

Enabled Hearing v2 flag on STAGING env

---

app/views/hearings/_details_v2.haml
spec/features/hearings_v2_spec.rb
spec/views/hearings/show.html.haml_spec.rb
spec/views/hearings/show_v2.html.haml_spec.rb

Use sitting_day for time_listed on V2 hearing day page
[AAC-689](https://dsdmoj.atlassian.net/browse/AAC-689)
Improve the accuracy of time_listed in V2 hearing day pages
Use hearing_day to acquire the time_listed from the sitting_day.
Test this with feature testing for now

AAC-689 BugFix - Use sitting_day for time_listed on V2 hearing day page

---

.k8s/live/production/deployment.yaml

What
Enable v2 Flag for Hearing page on PRODUCTION environment
Ticket
[CDUI - Enable Population of Hearing Day Via V2](https://dsdmoj.atlassian.net/browse/AAC-628)
Why
Upgrade will lead to performance increase for users on VCD
How
Update Kubernetes deployment.yaml file for production env

Enable v2 HEARING flag on PRODUCTION

---

app/controllers/application_controller.rb
app/models/cd_api/base_model.rb
app/models/current.rb
config/initializers/logstasher.rb

Start the correlation-id journey from the VCD frontend so that we can trace calls throughout the journey
[CDUI: Add laa-transaction-id to the start of the journey](https://dsdmoj.atlassian.net/browse/AAC-688)
Better tracability when debugging
- Set request_id in application controller, for incoming and outgoing requests
- set laa-transaction-id header based on this request_id
- Add the id to logs
Log entry below shows correlation between the 2 services.
https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/kibana#/discover?_g=(refreshInterval:(pause:!t,value:0),time:(from:now-2w,to:now))&_a=(columns:!(_source),index:'45bb7370-00eb-11ec-b879-8f5b8a74f645',interval:auto,query:(language:kuery,query:'194a6d538921f075d95491f0947fa9c2'),sort:!(!('@timestamp',desc)))

AAC-688 - laa-transaction-id journey from cdui

---

.circleci/config.yml

[CD UI: Remove testing steps from deploy to master workflow](https://dsdmoj.atlassian.net/browse/AAC-696)
The jobs aren't needed to run in this context, this will reduce deployment time
Remove all jobs before build-app-container in test-build-deploy-master workflow
Remove depedency of the removed jobs 
Changed name of test-build-deploy-master workflow to build-deploy-master
Apply a filter to the build-deploy-master workflow to only run on the master branch

Remove test steps from test-build-deploy-master

---

.gitignore
Makefile
app/views/devise/sessions/new.html.haml
cypress.config.js
cypress.env.json
cypress.json
cypress/config/dev.config.js
cypress/config/develop.json
cypress/config/prod.config.js
cypress/config/production.json
cypress/config/stage.config.js
cypress/config/staging.json
cypress/config/uat.config.js
cypress/config/uat.json
cypress/e2e/index/sign_in.cy.js
cypress/fixtures/example.json
cypress/fixtures/users.json
cypress/support/commands.js
docs/testing.md
package.json

- Update config files to use the new js format supported by cypress 10
- Add testing command to the MAKE file
- Update the login view with data-cy attributes
- Add initial sign in tests and fixture
- Add command for login
- Update readme
[Test user login](https://dsdmoj.atlassian.net/browse/AAC-152)
Allow for E2E test suite to run within CD UI

AAC-152 - Add initial sign in tests

---

cypress/config/dev.config.js
cypress/config/prod.config.js
cypress/config/stage.config.js
cypress/config/uat.config.js
cypress/e2e/cookies/cookie_banner.cy.js
cypress/e2e/cookies/cookie_information.cy.js
cypress/e2e/cookies/cookie_settings.cy.js
cypress/e2e/index/sign_in.cy.js
cypress/support/commands.js
cypress/support/e2e.js
package.json
yarn.lock

- Adds in accessibility testing to existing tests
- Adds commands for future testing
[Setup accessibility testing and linting in Cypress](https://dsdmoj.atlassian.net/browse/AAC-329)
E2E testing for CD UI

AAC-329 - Add in accessibility testing

---

app/views/layouts/cookie_banner/_success.html.haml

Remove Turbo Stream from cookie banner
[AAC-748](https://dsdmoj.atlassian.net/browse/AAC-748?atlOrigin=eyJpIjoiZjUxOTE2ZjQ2YWM5NGU4OTlkOWU4OGQ1ZmYwOWVlMWIiLCJwIjoiaiJ9)
Turbo Stream is not required for the cookie banner. Instead, we are using Turbo Frames
Remove turbo-stream from the cookie banner view partials
--------

AAC-748 Remove Turbo Stream from cookie banner

---

.k8s/live/dev/ingress.yaml
.k8s/live/production/ingress.yaml
.k8s/live/staging/ingress.yaml
.k8s/live/uat/ingress.yaml

Block the ip address of the user that is attempting php injection attacks on our service
[AAC-766](https://dsdmoj.atlassian.net/browse/AAC-766)
Keeps our service secure and reduces 404 alerts
Update the Deny list for DEV, UAT, Staging and Production to include the culprit IP

AAC-766 Block IP address of PHP attempts on service

---

app/decorators/prosecution_case_decorator.rb

- Update the table sorter to deal with unique hearingIds to prevent duplication with MDH.
[CD UI - MDH show 3 times](https://dsdmoj.atlassian.net/browse/AAC-768)
Hearings with Multiple days were coming through the V1 API multiple times (probably because of the different days) and because of the way we construct the interface in V1 this was replicating the days. 
Adding a uniq on the ID for the hearing, we should be able to correctly split everything out and only show what is available now.

AAC-768 - Unique sorted hearings

---

.haml-lint_todo.yml
app/views/defendants/_offences.html.haml
app/views/defendants/_offences_v2.html.haml
app/views/defendants/_representation_orders.html.haml
app/views/hearings/_raw_response.html.haml
app/views/prosecution_cases/_raw_response.html.haml
app/views/prosecution_cases/cd_api/_raw_response.html.haml

Fix HAML Linting Issues: UnnecessaryStringOutput
[AAC-706](https://dsdmoj.atlassian.net/browse/AAC-706)
As part of introducing code linting to check for stylistic errors and issues with our HAML files - we need to eliminate the day 0 lints in our code. 
As stated in the [UnnecessaryStringOutput](https://www.rubydoc.info/gems/haml_lint/HamlLint/Linter/UnnecessaryStringOutput) lints doc. 
The following two code snippets are equivalent, but the latter is more concise (and thus preferred):
```
%tag= "Some #{expression}"
%tag Some #{expression}
```
Reducing code by eliminating double quotes and equal characters
--------

aac-706/HAML-linting-UnnecessaryStringOutput

---

.k8s/live/dev/ingress.yaml

Update dev ingress to use new controller as per [this documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/Switch-ingress-to-v1-ingress-controller.html#switch-to-the-new-nginx-ingress-controller)
[CDUI - Update Ingress for new Cloud Platforms controller](https://dsdmoj.atlassian.net/browse/AAC-806)
To maintain compatibility with Cloud Platform

AAC-806 - Update dev ingress

---

.k8s/live/staging/ingress.yaml

Update staging ingress to use new controller as per [this documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/Switch-ingress-to-v1-ingress-controller.html#switch-to-the-new-nginx-ingress-controller)
[CDUI - Update Ingress for new Cloud Platforms controller](https://dsdmoj.atlassian.net/browse/AAC-806)
To maintain compatibility with Cloud Platform

AAC-806 - Update Staging ingress to use new controller

---

.k8s/live/uat/ingress.yaml

Update uat ingress to use new controller as per [this documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/Switch-ingress-to-v1-ingress-controller.html#switch-to-the-new-nginx-ingress-controller)
[CDUI - Update Ingress for new Cloud Platforms controller](https://dsdmoj.atlassian.net/browse/AAC-806)
To maintain compatibility with Cloud Platform

AAC-806 - Update UAT Ingress

---

.k8s/live/uat/deployment.yaml

Enable V2 on prosecution case and hearings page and in the UAT environment
[AAC-692 Hearing Day](https://dsdmoj.atlassian.net/browse/AAC-692)
[AAC-629 Prosecution Case](https://dsdmoj.atlassian.net/browse/AAC-629)
To enabled V2 CDAPI calls on the prosecution case and hearing day pages.
Set HEARING_SUMMARIES and HEARING env variable to true in UAT

AAC-629 & AAC-692 Enable V2 on prosecution case and hearing day page in UAT

---

.k8s/live/staging/deployment.yaml

Enable V2 on prosecution case page in the **STAGING** environment
[AAC-629 Prosecution Case](https://dsdmoj.atlassian.net/browse/AAC-629)
To enabled V2 CDAPI calls on the prosecution case pages.
Set HEARING_SUMMARIES env variable to **true** in DEV
Set HEARING_SUMMARIES env variable to **false** in UAT, Staging and Prod
Its counterpart page - Hearing day page - is already on V2 in Staging and thus already set to true in the config.

AAC-629 Enable V2 on prosecution case page in Staging

---

.k8s/live/production/ingress.yaml

Update prod ingress to use new controller as per [this documentation](https://user-guide.cloud-platform.service.justice.gov.uk/documentation/networking/Switch-ingress-to-v1-ingress-controller.html#switch-to-the-new-nginx-ingress-controller)
[CDUI - Update Ingress for new Cloud Platforms controller](https://dsdmoj.atlassian.net/browse/AAC-806)
To maintain compatibility with Cloud Platform

AAC-806 - Update prod ingress

---

.k8s/live/production/deployment.yaml

Enable V2 on the prosecution case and hearing day pages in **Production**
[AAC-692 Hearing Day](https://dsdmoj.atlassian.net/browse/AAC-692)
[AAC-629 Prosecution Case](https://dsdmoj.atlassian.net/browse/AAC-629)
To enable V2 calls on the prosecution case and hearing day pages
Set HEARING_SUMMARIES and HEARING env variable to true in the k8s  **Production** deployment config file

AAC-629 AAC-692 Enable V2 on prosecution case and hearing day page in Production

---

app/decorators/cd_api/overall_defendant_decorator.rb
app/models/cd_api/defendant.rb
app/models/cd_api/laa_application.rb
app/models/cd_api/offence_summary.rb
app/views/prosecution_cases/cd_api/_overall_defendants.html.haml
spec/decorators/cd_api/overall_defendant_decorator_spec.rb
spec/factories/cd_api/defendant.rb
spec/factories/cd_api/laa_application.rb
spec/factories/cd_api/offence_summary.rb
spec/models/cd_api/defendant_spec.rb

CDUI V2 - Do not display dummy MAAT references prefixed with 'Z'
[AAC-781](https://dsdmoj.atlassian.net/browse/AAC-781)
We should ignore maat references prefixed with 'Z' and assume the Defendant is not linked. The reason these references exist is due to a limitation in Common Platform with being unable to remove MAAT references, the Z reference is a placeholder to show removal - to show this to our users would cause confusion regarding whether a case has legal aid granted and has been correctly linked between MLRA and Common Platform.
Added a check in the linked? method in orverall_defendant_decorator to check for the first character of the maat_references and returning false if it starts with "Z" and directing user to the correct endpoint (laa_references).
`maat_reference&.present? && …

aac-781 MAAT ref check and view change

---

app/decorators/cd_api/defence_counsel_decorator.rb
app/decorators/cd_api/hearing_summary_decorator.rb
spec/decorators/cd_api/defence_counsel_decorator_spec.rb
spec/decorators/cd_api/hearing_summary_decorator_spec.rb
spec/factories/cd_api/defendant.rb
spec/factories/cd_api/hearing_summary.rb

Display the provider and defendant relationship
[AAC-325](https://dsdmoj.atlassian.net/browse/AAC-325)
- map defence_counsel.defendants (ids) to hearing summary.defendants (objects)
- Include defendants info to the defence counsel list
- Add unit testing
The defence counsels has a list of defendant_ids that they each represent. This does not contain the defendant information like first name and last name. Thus mapped the defendant data in the hearing summary to it.
Defence counsel list is now: "Defence Counsel Name (status) for Defendant A"
or when it's multiple defendants it's 
"Defence Counsel1 Name (status) for Defendant A< br>Defence Counsel1 Name (status) for Defendant B< br>Defence Counsel2 Name (QC) for Defendant C"

AAC-325 Display the provider and defendant relationship

---

app/views/layouts/application.html.haml
app/webpack/packs/application.js
app/webpack/packs/govuk-frontend.js

Move the GOVUK initAll() function to an event listener so that it always gets fired for turbo. 
[BUG - VCD - Applications not always appearing properly](https://dsdmoj.atlassian.net/browse/AAC-852)
Turbo does not do page refreshing as it treats the site as a Single Page application. Because of this the initAll function is not always called and therefor GOVUK functionallity breaks. 
Move to its own packed file and add to event listener.

AAC-852 - Move initall to eventlistener for turbo

---

.rubocop.yml
app/controllers/hearings_controller.rb
app/decorators/cd_api/hearing_decorator.rb
app/decorators/cd_api/hearing_summary_decorator.rb
spec/decorators/cd_api/hearing_decorator_spec.rb
spec/decorators/cd_api/hearing_summary_decorator_spec.rb
spec/factories/cd_api/hearing_day.rb
spec/fixtures/stubs/cd_api/hearing_data_response.json
spec/views/hearings/_attendees_v2.html.haml_spec.rb
spec/views/prosecution_cases/cd_api/_hearing_summaries.html.haml_spec.rb

AAC-828 Filter DefenceCounsels on attendance days for the **Case Page and Hearing day Page**
[AAC-828](https://dsdmoj.atlassian.net/browse/AAC-828)
To filter out defence counsels that did not attend a particular hearing day of a multi-day hearing.
Defence Counsels have property :attendance_days, which needs to be used when creating the Providers Attending or Defence Advocates lists on the Case page and Hearing day pages respectively. 
- Add current_sitting_day to the hearing decorator, in order to know what the current hearing day is being called. This is used to compare with the defence counsels.attendance_days
- Add logic to not show defence_counsels where their attendance_days does not include the hearing day being worked on.
- Filter out defence_counsels where the hearing_summary.day …

AAC-828 BugFix Filter DefenceCounsels on attendance days

---

app/decorators/cd_api/case_summary_decorator.rb
app/decorators/cd_api/hearing_summary_decorator.rb
app/views/prosecution_cases/cd_api/_hearing_summaries.html.haml
config/locales/en/decorators/hearing_summary.yml
spec/decorators/cd_api/hearing_summary_decorator_spec.rb
spec/factories/cd_api/hearing_summary.rb
spec/views/prosecution_cases/cd_api/_hearing_summaries.html.haml_spec.rb

Caseworkers need to see estimated duration when assessing interim bills and cracked trials, as it changes the claimable fee when a trial estimate breaches a threshold of length.
[Show Trial Estimation of Hearing](https://dsdmoj.atlassian.net/browse/AAC-425)
We added the estimated duration to trials on the case summary page hearings table. This will allow our users to easily identify the trials estimations and authorise interim and cracked trial bills.
Added method to format estimated duration string in hearing_summary decorator.
Added styling and estimated duration call to hearing_summaries view.
Updated case_summary decorator to set 'estimated_duration' to nil for future multi day hearings. This ensures estimated duration is only shown on the first hearing day.
Updated unit tests.

AAC-425 Show Trial Estimation of Hearing

---

.k8s/live/dev/ingress.yaml
.k8s/live/production/ingress.yaml
.k8s/live/staging/ingress.yaml
.k8s/live/uat/ingress.yaml

Update ingress deny list to prevent malicious [attempts](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-09-26T04:00:00.000Z',to:'2022-09-26T04:30:00.000Z'))&_a=(columns:!(_source),filters:!(),index:'167701b0-f8c0-11ec-b95c-1d65c3682287',interval:auto,query:(language:lucene,query:'%22laa-court-data-ui-production%22%20AND%20%22404%22'),sort:!('@timestamp',desc))) on our service by certain ip addresses
on all environments (DEV, UAT, Staging and Production).
[VCD - Block Rogue IP addresses from Path scanning application](https://dsdmoj.atlassian.net/browse/AAC-888)
To prevent malicious hacks on our service.
Update the ingress files for each environment and deny the culprits/IP addresses.

AAC-888 Block Bot IP addresses in all environments

---

app/decorators/cd_api/hearing_decorator.rb
app/models/cd_api/prosecution_counsel.rb
app/views/hearings/_attendees_v2.html.haml
spec/decorators/cd_api/hearing_decorator_spec.rb
spec/factories/cd_api/hearing/prosecution_case.rb
spec/factories/cd_api/hearing/prosecution_counsel.rb
spec/features/hearings_v2_spec.rb
spec/fixtures/stubs/cd_api/hearing_data_response.json
spec/views/hearings/_attendees_v2.html.haml_spec.rb

Filter out prosecution counsels that did not attend the particular hearing day on the Hearing day page.
[AAC-868 BUG - Multi Day Trial Prosecution Advocates display](https://dsdmoj.atlassian.net/browse/AAC-868)
So users aren't mislead into believing a prosecution counsel member attended a hearing day on a multiday hearing, when they didn't.
Filter out the prosecution counsels where their attendance_days does not include the current_hearing_day on the hearing page.
Add unit and feature tests

AAC-868 Filter Prosecution Counsels on hearing day page

---

.circleci/config.yml

Remove the version lock on the Docker dependency in CircleCI so we can always get the latest for security and feature updates. 
[CD UI - Remove Docker Version from CircleCI](https://dsdmoj.atlassian.net/browse/AAC-908)
Potential Deprecation of features in older versions

AAC-908 - Update CircleCi Config

---

.rubocop.yml
spec/decorators/cd_api/case_summary_decorator_spec.rb
spec/decorators/cd_api/cracked_ineffective_trial_decorator_spec.rb
spec/decorators/cd_api/defence_counsel_decorator_spec.rb
spec/decorators/cd_api/hearing_day_decorator_spec.rb
spec/decorators/cd_api/hearing_decorator_spec.rb
spec/decorators/cd_api/hearing_summary_decorator_spec.rb
spec/decorators/cd_api/overall_defendant_decorator_spec.rb
spec/factories/cd_api/case_summary.rb
spec/factories/cd_api/hearing.rb
spec/factories/cd_api/hearing/defendant.rb
spec/factories/cd_api/hearing/defendant_details.rb
spec/factories/cd_api/hearing_summary.rb
spec/factories/cd_api/offence_summary.rb
spec/factories/cd_api/overall_defendant.rb
spec/models/cd_api/defendant_spec.rb
spec/models/unlink_reasons_spec.rb
spec/services/cd_api/hearing_details/defence_counsels_list_service_spec.rb
spec/support/shared_examples_for_hearings_sorters_v2.rb
spec/views/hearings/show_v2.html.haml_spec.rb
spec/views/prosecution_cases/cd_api/_hearing_summaries.html.haml_spec.rb
spec/views/prosecution_cases/cd_api/_overall_defendants.html.haml_spec.rb
spec/views/prosecution_cases/cd_api/_show_v2.html.haml_spec.rb

Fix Rubocop issues for [`RSpec/FactoryBot/ConsistentParenthesesStyle`](https://docs.rubocop.org/rubocop-rspec/cops_rspec_factorybot.html#rspecfactorybotconsistentparenthesesstyle)
[Fix Rubocop Issues: RSpec/FactoryBot/ConsistentParenthesesStyle](https://dsdmoj.atlassian.net/browse/CTSKF-53)
Maintain consistent coding style.
All of the changes have been auto-fixed. In one place, in `spec/support/shared_examples_for_hearings_sorters_v2.rb`, a line has been broken to keep within the line length limit.
By default, parentheses are preferred so
```ruby
let(:case_summary) { build :case_summary }
```
becomes
```ruby
let(:case_summary) { build(:case_summary) }
```
It is possible to change the behaviour so that the former version, without parenthesis, is enforced. Which is preferred? Using this …

[CTSKF-53] Rubocop: Fix RSpec/FactoryBot/ConsistentParenthesesStyle

---

.circleci/build.sh
.circleci/deploy.sh

Use `get-login` instead of `get-login-password`
[Deployment fails with deprecated AWS login message](https://dsdmoj.atlassian.net/browse/CTSKF-165)
`get-login` has been deprecated and is now causing deployments to fail.

Update ECR login mechanism

---

.circleci/config.yml

Improve the performance of CircleCI parallel testing
no ticket
This should provide performance benefits / optimize with each test suite run
more info: https://circleci.com/docs/parallelism-faster-jobs/#how-test-splitting-works
Update the circleci config for parallelism to split tests by timings rather than the default of splitting tests by name

Update CircleCI parallelism to split by timings

---

.circleci/config.yml

Increase the SNYK scan threshold to `critical`
This is because there is a `high` vulnerability blocking the CI/CD pipeline. This is a temporary change until the venerability is resolved (relating to webpacker)
Update the Circlci config > snyk/scan --severity-threshold to "critical"

Increase the SNYK scan threshold to critical

---

.k8s/live/dev/ingress.yaml
.k8s/live/production/ingress.yaml
.k8s/live/staging/ingress.yaml
.k8s/live/uat/ingress.yaml

**What**
Update ingress deny list to prevent malicious [attempts](https://kibana.cloud-platform.service.justice.gov.uk/_plugin/kibana/app/discover#/doc/167701b0-f8c0-11ec-b95c-1d65c3682287/live_kubernetes_cluster-2023.03.06?id=ca11b54f-6dea-036b-af26-07ee7fbb358c) on our service by certain ip addresses
on all environments (DEV, UAT, Staging and Production).
**Ticket**
[CTSK291](https://dsdmoj.atlassian.net/browse/CTSKF-291)
**Why**
To prevent malicious hacks on our service.
**How**
Update the ingress files for each environment and deny the culprits/IP addresses.

CTSKF-291 Update ip blocklist with bot ip

---

package.json
yarn.lock

Bump JavaScript packages.
[CTSKF-366](https://dsdmoj.atlassian.net/browse/CTSKF-366)
Maintenance of our application dependencies helps to keep our service secure, reliable and accurate.
Group the Dependabot JavaScript packages into one PR:
1. [Bump @babel/core](https://github.com/ministryofjustice/laa-court-data-ui/pull/1484)
2. [Bump @babel/preset-env](https://github.com/ministryofjustice/laa-court-data-ui/pull/1483)
3. [Bump stylelint-config-gds](https://github.com/ministryofjustice/laa-court-data-ui/pull/1480)
4. [Bump webpack](https://github.com/ministryofjustice/laa-court-data-ui/pull/1477)
5. [Bump cypress](https://github.com/ministryofjustice/laa-court-data-ui/pull/1476)
6. [Bump sass](https://github.com/ministryofjustice/laa-court-data-ui/pull/1475)
7. [Bump …

CTSKF-366 Update frontend packages via grouping dependabot updates

---

app/controllers/laa_references_controller.rb
spec/features/defendants_view_spec.rb
spec/requests/defendants_spec.rb

Provide cleaner method of displaying an error when there are multiple MAAT errors on the V1 endpoint. CDA had changed the error from a 500 to the 422 which provided unuseful errors
[CD UI: Misleading Error Message Shows When Trying to Access Defendant Page ](https://dsdmoj.atlassian.net/browse/CTSKF-398)
Provide better feedback to the end user
Explicitly catch the error occuring and returning them back to the search results rather than throw error pages.

CTSKF-398 - Be explicit in error catch and handle in cleaner method

---

app/controllers/application_controller.rb
app/controllers/defendants_controller.rb
app/controllers/laa_references_controller.rb
app/controllers/searches_controller.rb
app/models/search.rb
config/locales/en/views/searches.yml
spec/features/search/cd_api/case_reference_spec.rb
spec/models/cd_api/search_spec.rb
spec/support/webmock/court_data_api/webmock.rb

Update the search page so that we reflect the error code being given to us. This means users will know if they are getting no results or if errors are occuring on the page. It also means we log and react to these errors
[CDUI - Handle 424 on searches page](https://dsdmoj.atlassian.net/browse/CTSKF-403)

CTSKF-403 - Return error flash when non 200 status code received

---

Gemfile
Gemfile.lock

Group Dependabot updates on ruby gemfiles for the below PRs:
[Bump sidekiq_alive from 2.2.0 to 2.2.1](https://github.com/ministryofjustice/laa-court-data-ui/pull/1501)
[Bump rubocop from 1.50.2 to 1.51.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1500)
[Bump capybara from 3.39.0 to 3.39.1](https://github.com/ministryofjustice/laa-court-data-ui/pull/1499)
[CTSKF-393](https://dsdmoj.atlassian.net/browse/CTSKF-393)
- Updating our dependencies keeps our application secure and functioning.
- Grouping the Dependabot updates makes the whole dependency management process quicker instead of testing each one in separate deployments, we can deploy and test in groups.
Update the Gemfile and/or Gemfile.lock version numbers of the dependencies.
[CTSKF-393]: …

CTSKF-393 Update ruby dependencies by grouping Dependabot updates

---

package.json
yarn.lock

Group Dependabot updates to the front end javascript package
These are all minor updates so i'm less worried about grouping all these updates.
[CTSKF-418 Release of dependancy and security updates](https://dsdmoj.atlassian.net/browse/CTSKF-418)
This keeps our application up to date, secure, maintained and working as expected.
Group the Dependabot updates using `git cherry-pick` . These commits were not authored by me, it was just copied over from Dependabot PRs.
Update the below:
[Bump webpack from 5.82.0 to 5.85.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1533/commits/00e3a39018b42bfa4bdccc8a86287290c7fcd25f)
[Bump standard from 17.0.0 to 17.1.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1533/commits/248a1e14ea26356fb84b16591dde1f66c01f95b9)
[Bump …

CTSKF-418 Update frontend dependencies by minor versions

---

.circleci/build.sh
.circleci/config.yml
.circleci/deploy.sh

Implements changes mandated by Cloud Platform to deprecate the use of long-lived ECR credentials:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/container-repositories/deprecating-long-lived-credentials.html#migrating-to-short-lived-credentials-for-circleci
[CTSKF-438](https://dsdmoj.atlassian.net/browse/CTSKF-438)
To allow the service to continue to be built and deployed to the MOJ Cloud Platform, while increasing the security of the process
* Adds the `aw-cli` orb to `.circleci/config.yml`
* Configures that orb to use the new `ECR_REGION` and `ECR_ROLE_TO_ASSUME` environment variables before building or deploying the app.
* Removes unnecessary references to the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables from the …

CTSKF-438 Use short-lived ECR credentials

---

package.json
yarn.lock

[CTSKF-471](https://dsdmoj.atlassian.net/browse/CTSKF-471)
[Bump sass from 1.63.2 to 1.63.6](https://github.com/ministryofjustice/laa-court-data-ui/pull/1569)
[Bump webpack from 5.85.1 to 5.88.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1567)
[Bump cypress from 12.14.0 to 12.15.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1564)
[Bump sass-loader from 13.3.1 to …

CTSKF-471 Update JS packages as a group of Dependabot updates

---

app/controllers/defendants_controller.rb
spec/requests/unlinking/unlink_defendant_maat_reference_v2_spec.rb

Update the use of the 'defendants.unlink.failure' translation to use an empty string if there are no error_messages passed to it.
[CTSKF-476](https://dsdmoj.atlassian.net/browse/CTSKF-476)
This fixes an issue with code is seen in the error message when CDA does not return an error message in its response
use an empty string in the parameter of error_messages `I18n.t('defendants.unlink.failure', error_messages: '')`
--------
[CTSKF-476]: https://dsdmoj.atlassian.net/browse/CTSKF-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CTSKF-476 BUGFIX Default error_messages parameter during MAAT unlinking

---

package.json
yarn.lock

[CTSKF-471](https://dsdmoj.atlassian.net/browse/CTSKF-471)
[Bump cypress from 12.15.0 to 12.16.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1580)
[Bump webpack from 5.88.0 to 5.88.1](https://github.com/ministryofjustice/laa-court-data-ui/pull/1582)
[Bump @rails/ujs from 7.0.5 to 7.0.6](https://github.com/ministryofjustice/laa-court-data-ui/pull/1583)
[Bump @babel/core from 7.22.5 …

CTSKF-471 Update JavaScript Dependencies by grouping dependabot updates

---

package.json
yarn.lock

[CTSKF-504](https://dsdmoj.atlassian.net/browse/CTSKF-504)
[Bump @babel/plugin-transform-runtime from 7.22.6 to 7.22.7](https://github.com/ministryofjustice/laa-court-data-ui/pull/1590)
[Bump postcss from 8.4.24 to 8.4.25](https://github.com/ministryofjustice/laa-court-data-ui/pull/1595)
[Bump cypress from 12.16.0 to 12.17.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1594)
[Bump …

CTSKF-504 Update JavaScript Dependencies by grouping Dependabot

---

.circleci/config.yml
spec/support/capybara.rb

Fix our automated feature tests by setting the version of the chrome browser for our WebDriver gem to a previous version `114.0.5735.90` temporarily until they fix their gem issue.
This fixes an error in our [CircleCI rspec tests](https://app.circleci.com/pipelines/github/ministryofjustice/laa-court-data-ui/8587/workflows/1a079992-76bb-4d36-8ecd-22d2ee987fa5/jobs/34156) that returns 404 for the latest version of chrome
```
Installed version of Google Chrome is 115.0.5790.102
curl: (22) The requested URL returned error: 404
```
[CTSKF-511](https://dsdmoj.atlassian.net/browse/CTSKF-511)
This will unblock our CI/CD pipeline so we can ship dependency updates and keep our application up to date, secure and reliable.
Set the version of the webdriver's chrome to `114.0.5735.90`
```
apt-get …
```

CTSKF-511 BugFix Temporarily set the webdriver chrome version to fix capybara tests

---

package.json
yarn.lock

[CTSKF-511](https://dsdmoj.atlassian.net/browse/CTSKF-511)
Group dependabot updates into one PR for:
[Bump stylelint from 15.10.1 to 15.10.2](https://github.com/ministryofjustice/laa-court-data-ui/pull/1617)
[Bump cypress from 12.17.1 to 12.17.2](https://github.com/ministryofjustice/laa-court-data-ui/pull/1618)
[Bump webpack from 5.88.1 to 5.88.2](https://github.com/ministryofjustice/laa-court-data-u …

CTSKF-511 Update JavaScript Dependencies by grouping Dependabot updates

---

Gemfile
Gemfile.lock
app/views/layouts/_phase_banner.html.haml

Group Ruby Dependabot minor and patch updates
[CTSKF-511](https://dsdmoj.atlassian.net/browse/CTSKF-511)
Grouping the Dependabot saves a lot of time testing and deploying.
[Bump sidekiq_alive from 2.2.2 to 2.2.3](https://github.com/ministryofjustice/laa-court-data-ui/pull/1620)
[Bump brakeman from 6.0.0 to 6.0.1](https://github.com/ministryofjustice/laa-court-data-ui/pull/1619)
[Bump rubocop from 1.54.1 to 1.54.2](https://github.com/ministryofjustice/laa-court-data-ui/pull/1611)
[Bump haml_lint from 0.47.0 to 0.49.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1612)
[Bump govuk_design_system_formbuilder from 4.0.0 to 4.1.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1610) …

CTSKF-511 grouped ruby dependency updates

---

package.json
yarn.lock

Update the cypress package.
https://github.com/ministryofjustice/laa-court-data-ui/security/dependabot/73
The security issue with @cypress/request cannot be addressed with cypress version lower than 13.
Update cypress to the latest version, 13.1.0.

Update cypress from 12.17.4 to 13.1.0

---

.circleci/config.yml
spec/support/capybara.rb

- Use the latests chrome webdriver version as part of tests
- Remove the fixed older version of chrome
- This reverts the temporary fix of this PR https://github.com/ministryofjustice/laa-court-data-ui/pull/1623
[CTSKF-511](https://dsdmoj.atlassian.net/browse/CTSKF-511)
So that the chrome web driver is using the latest version and thus the feature tests run on something more akin to what users are using atm.
Remove the fixing of the chrome web driver version in the circle config and the capybara config file
[CTSKF-511]: https://dsdmoj.atlassian.net/browse/CTSKF-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CTSKF-511 Undo the fixing of the chrome webdriver version

---

package.json
yarn.lock

[CTSKF-578](https://dsdmoj.atlassian.net/browse/CTSKF-606)
Except the stylelint bump which is a major update. Although i believe its impact would be minimal if it were to break.
Group Dependabot updates into one PR for:
[Bump sass from 1.68.0 to 1.69.5](https://github.com/ministryofjustice/laa-court-data-ui/pull/1759)
[Bump cypress from 13.3.1 to …

CTSKF-606 Update JS dependencies

---

app/controllers/users/sessions_controller.rb
app/views/layouts/_navigation.html.haml

Fix the user sign out feature after a bug was introduced by this PR [@rails/ujs to 7.1.1]  (https://github.com/ministryofjustice/laa-court-data-ui/pull/1738) 
[CTSKF-606](https://dsdmoj.atlassian.net/browse/CTSKF-606)
In order to use Turbo for the link_to user destroy method. This was after upgrading [@rails/ujs to 7.1.1]  (https://github.com/ministryofjustice/laa-court-data-ui/pull/1738) which caused our cucumber tests to break around the alert box after deleting a user. The solution to that was to use Turbo - the new way of doing what @rails/ujs did. There may be a flickering cucumber test but not nearly as much as when we used rails/ujs for the alertboxes.
Override Devise destroy method to use the :see_other http status 303 because this will Turbo rails requires it to.
on github …

CTSKF-606 BugFix Users are being sent to /404 page after sign out

---

spec/features/users/delete_user_spec.rb

Wait for up to 2 seconds for the modal/alert box to appear.
[CTSKF-615](https://dsdmoj.atlassian.net/browse/CTSKF-615)
This should hopefully fix the flickering test in our CI/CD tests:
Failures:
1) Delete user when manager can index and delete users
Failure/Error: warning = page.driver.browser.switch_to.alert
Selenium::WebDriver::Error::NoSuchAlertError:
no such alert
(Session info: headless chrome=[redacted])
Use [Capybara::Session#accept_alert](https://www.rubydoc.info/gems/capybara/Capybara%2FSession:accept_alert) to wait for the alert box for up to 2 seconds.
[CTSKF-615]: https://dsdmoj.atlassian.net/browse/CTSKF-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

CTSKF-615 BugFix Alert box not appearing in tests after deleting a user

---

package.json
yarn.lock

[CTSKF-615](https://dsdmoj.atlassian.net/browse/CTSKF-615)
Group Dependabot updates into one PR for:
[Bump cypress from 13.3.3 to 13.6.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1792)
[Bump @babel/plugin-transform-runtime from 7.23.2 to 7.23.4](https://github.com/ministryofjustice/laa-court-data-ui/pull/1791)
[Bump @ministryofjustice/frontend](https://github.com/ministryofjustice/ …

CTSKF-615 Update JavaScript dependencies

---

package.json
yarn.lock

[CTSKF-615](https://dsdmoj.atlassian.net/browse/CTSKF-615)
Group Dependabot updates into one PR for:
[Bump cypress from 13.3.3 to 13.6.1](https://github.com/ministryofjustice/laa-court-data-ui/pull/1808)
[Bump postcss from 8.4.31 to 8.4.32](https://github.com/ministryofjustice/laa-court-data-ui/pull/1805)
[Bump @babel/preset-env from 7.23.2 to …

CTSKF-615 Update JS dependencies 2

---

package.json
yarn.lock

[CTSKF-637](https://dsdmoj.atlassian.net/browse/CTSKF-637)
Group Dependabot updates into one PR for:
[Bump @babel/core from 7.23.5 to 7.23.7](https://github.com/ministryofjustice/laa-court-data-ui/pull/1837)
[Bump @babel/preset-env from 7.23.5 to 7.23.7](https://github.com/ministryofjustice/laa-court-data-ui/pull/1836)
[Bump @babel/plugin-transform-runtime from 7.23.4 to …

CTSKF-637 Update js dependencies

---

app/models/cd_api/defendant.rb
app/views/defendants/_defendant.html.haml
spec/models/cd_api/defendant_spec.rb

Get the V2 Defendant **MAAT Reference** from the `defendant_summaries["offence_summaries"]` array
[board ticket description](link)
The true source of maat_reference in the V2 API is from the `defendant_summaries["offence_summaries"]` data not from the `defendant_summaries["representation_order"]`.
- Add maat_reference method to CDAPI::Defendant model
- Get the maat_reference from the offence_summaries not the representation_order object in the defendant results json
- Update test for the new public method CDAPI::Defendant#maat_reference

Get the Defendant MAAT Reference from the offence_summaries array

---

Gemfile
Gemfile.lock

1. Group Ruby Dependabot minor and patch updates
[CTSKF-685](https://dsdmoj.atlassian.net/browse/CTSKF-685)
Grouping the Dependabot saves a lot of time testing and deploying.
[Bump capybara from 3.39.2 to 3.40.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1880)
[Bump rspec-rails from 6.1.0 to 6.1.1](https://github.com/ministryofjustice/laa-court-data-ui/pull/1875)
[Bump activeresource from 6.0.0 to 6.1.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1873)
[Bump haml_lint from 0.52.0 to 0.55.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1870)
[Bump axe-core-rspec from 4.8.0 to 4.8.1](https://github.com/ministryofjustice/laa-court-data-ui/pull/1863) …

CTSKF-685 Update ruby dependencies

---

Gemfile
Gemfile.lock
package.json
yarn.lock

Bump @hotwired/turbo-rails from 8.0.1 to 8.0.2 #1912
Bump sass from 1.70.0 to 1.71.0 #1921
Bump turbo-rails from 2.0.1 to 2.0.3 #1924
[Bump govuk_design_system_formbuilder from 5.0.0 to 5.1.0](https://github.com/ministryofjustice/laa-court-data-ui/pull/1927)
Bump selenium-webdriver from 4.17.0 to 4.18.1 #1928
Bump webpack from 5.90.1 to 5.90.3 #1929
Bump webmock from 3.20.0 to 3.21.2 #1931
Release of dependency and security updates - Sprint I[CTSKF-705](https://dsdmoj.atlassian.net/browse/CTSKF-705)
Update dependencies by grouping Dependabot updates in order to keep our app up to date with security fixes/patches and feature updates so that it continues to run successfully, accurately and securely.

Ctskf 705 dependabot pr

---

.circleci/config.yml
.github/dependabot.yml
package.json
yarn.lock

Upgrade the cypress package to 13.14.1
[Investigate VCD Snyk Docker Image Security Alert](https://dsdmoj.atlassian.net/browse/CTSKF-881)
Snyk is reporting issues and this is blocking the pipeline. This can be resolved by upgrading the cypress package to the latest version.
* Set the required version in `package.json`.
* Update the synk orb to version 2.2.0.
* Set the 'no output timeout' for the Snyk scan to 20 minutes. This seems to be the [recommendation in the README file.](https://github.com/snyk/snyk-orb)
* Update the dependabot configuration so that sub-dependencies get updated.

[CTSKF-881] Upgrade the cypress npm package to 13.14.1

---

Gemfile
Gemfile.lock

Upgrade `json_api_client` and `faraday_middleware` together.
N/A
`json_api_client` has been updated to allow compatibility with both version 1 and 2 of Faraday. To do this the `faraday_middleware` gem was removed as this is not compatible with Faraday version 2. To facilitate this some middleware has been built in to Faraday 1 to mirror the behaviour of version 2. This has been done for the JSON firmware, which `json_api_client` uses, but not for the OAuth2 middleware, which we still require. Simply adding `faraday_middleware` back in for the OAuth2 middleware causes conflicts as the JSON middleware exists twice.
Add `faraday_middleware` and require at least version 1.2.1. This version has been fixed (https://github.com/lostisland/faraday/pull/1595) to resolve conflicts and favours the …

Upgrade json_api_client

---

config/application.rb
config/initializers/devise.rb
docker/Dockerfile

Changes the email address listed on the contact page, the email address used by the email service, and the email address listed as the maintainer of the Docker image.
[Change all instances of assess-a-claim email to Access-Court-Data where possible](https://dsdmoj.atlassian.net/browse/ACD-590)
The old email address was that of the team that previously owned the service, as opposed to the one that now does.
The email address is set explicitly in the Docker file. The other two instances are variables used in places throughout the survey.

ACD-590 - Change email address to new team's address

---

Gemfile.lock
app/views/layouts/application.html.haml
public/robots.txt

Instruct Google and other crawlers not to index the site in any environment. 
[Hide VCD from search engines](https://dsdmoj.atlassian.net/browse/ACD-594)
Because these pages are not for public consumption and their presence on Google may cause confusion.
"VCD’s intended users have other ways of getting the link (from emails, intranet, bookmarks etc) so the downsides of it being on search engines outweigh any benefits."
Do this by:
~- Adding a global directive in robots.txt~
- Adding a `meta` tag on each individual page
(robots.txt tells crawlers whether they can crawl pages. SInce Google already has crawled our pages and believes the content is indexable, we want to allow the crawlers to keep crawling so they at some point crawl back and notice that the pages are now `noindex`.)
Note that …

ACD-594: Disallow indexing

---

app/models/cd_api/defendant.rb
spec/factories/cd_api/defendant.rb
spec/models/cd_api/defendant_spec.rb

On UAT, when trying to establish if a defendant is linked by MAAT ID when showing the "raw data" in the UI, we hit an error looking for "offence_summaries" when we've only defined "offence_summary". Note that this doesn't show up in the test suite because our FactoryBot factory plus ActiveResource combine to make our test fixtures actually have an "offence_summaries" attribute even though it's not defined on the class.

BUG: Fix typo

---

app/decorators/cd_api/hearing_summary_decorator.rb
spec/decorators/cd_api/hearing_summary_decorator_spec.rb

When using the v2 endpoints/CDAPI, whenever the `/prosecution_cases/<id>` screen is accessed, `TableSorters::HearingsProviderSorter` sorts the hearings by the defence_counsel_list property. `HearingSummaryDecorator#defence_counsel_list` calls a method called `attended_defence_counsels` which assumes that the hearing summary has a `day` attribute set. _HOWEVER_, hearings do not have a "day" by default (because hearings can run over multiple days). The `day` attribute is only set when the hearing summary object is being used to display information about a specific day of the many which can be associated with a hearing (e.g. `CaseSummaryDecorator#sorted_hearing_summaries_with_day`). At the point of sorting, `day` has not been set, so `day.strftime` in `attended_defence_counsels` errors out. …

ACD-255: Sorting hearing counsels

---

app/models/cd_api/defendant.rb
spec/models/cd_api/defendant_spec.rb

When `GET <cd api>/v2/offence_summaries?defendant_id=<id>` returns a 404 (common on UAT), `CdApi::Defendant#offence_summaries` is nil, so `#maat_references` raises an error.
This is related to the previous bug where `offence_summaries` didn't exist at all, as it was only defined on the model as `offence_summary`. I should have checked more UAT cases before merging.

BUG: Handle nil offence summaries

---

app/controllers/court_applications_controller.rb
app/views/court_applications/show.html.haml
config/locales/en/views/court_applications.yml
config/routes.rb
lib/court_data_adaptor/resource/application_hearing.rb
lib/court_data_adaptor/resource/application_summary.rb
lib/court_data_adaptor/resource/defence_counsel.rb
lib/court_data_adaptor/resource/hearing_day.rb
spec/features/court_applications_spec.rb
spec/fixtures/vcr_cassettes/spec/features/court_applications_spec.yml
spec/lib/court_data_adaptor/resource/application_hearing_spec.rb
spec/lib/court_data_adaptor/resource/application_summary_spec.rb

Add a date-sortable hearings table that shows a row for each hearing day, with the hearing type defence counsels that attended on that day.
[As a caseworker I want to see a hearings summary](https://dsdmoj.atlassian.net/browse/ACD-527)

ACD-527: Hearing overview

---

.rubocop.yml
Gemfile
Gemfile.lock
config/application.rb

- Remove CSV and Timezone warnings.
- Specify plugins instead of require: rubocop-capybara
For more information, see https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
no ticket
to keep VCD udpated

Remove warnings

---

.circleci/config.yml
.rubocop.yml
Gemfile
Gemfile.lock
lib/tasks/simplecov/process_coverage.rake
spec/rails_helper.rb

VCD coverage is currently >99% line and >85% branch, but this isn't enforced anywhere. Enabling it in CI is not totally straightforward as specs are run in parallel on multiple containers, so coverage has to be collated before it can be measured.
https://dsdmoj.atlassian.net/browse/ACD-661
This PR:
- Removes some old codeclimate code that was sending coverage stats off to a third party
- Cribs from https://github.com/ministryofjustice/laa-submit-crime-forms to stash coverage files in CI and run a rake task to collate them and flag up if coverage falls below the minimum.

ACD-661: Enforce coverage in CI

---

.k8s/live/dev/deployment-worker.yaml
.k8s/live/dev/deployment.yaml
.k8s/live/production/deployment-worker.yaml
.k8s/live/production/deployment.yaml
.k8s/live/staging/deployment-worker.yaml
.k8s/live/staging/deployment.yaml
.k8s/live/uat/deployment-worker.yaml
.k8s/live/uat/deployment.yaml

We are creating new `aws-secrets` which are backed by AWS secret manager, giving us accidental deletion protection as well as a nice UI for secret access and rotation. This PR updates VCD to pull secret values from the new secret
[Migrate VCD secrets to AWS secret manager](https://dsdmoj.atlassian.net/browse/ACD-668)

ACD-668: Switch to AWS secrets

---

app/controllers/hearing_days_controller.rb
app/decorators/cd_api/hearing_decorator.rb
app/views/hearing_days/show.html.haml
spec/features/application_hearings_spec.rb
spec/fixtures/vcr_cassettes/spec/features/application_hearings_spec.yml

Court applications come with a list of hearing summaries, including unresulted hearings. We link to a hearing details page for each hearing summary. On the hearing details page we try to load hearing details from HMCTS. But we believe (based on how it works for prosecution case hearings) that HMCTS will return a blank response for hearing details which CDA will turn into a 404. For prosecution cases we gracefully handle this.
This PR adds the same graceful handling logic to court application hearings that we already have for prosecution case hearings, so that we don't crash when viewing details of unresulted hearings.

ACD-700: Do not crash if hearings are unresulted

---

app/assets/javascript/application.js
app/views/cookies/_form.html.haml
app/views/devise/passwords/new.html.haml
app/views/devise/sessions/new.html.haml
app/views/devise/unlocks/new.html.haml
app/views/searches/_form.html.haml
app/views/users/_form.html.haml
app/views/users/change_password.html.haml
config/locales/en/views/layouts.yml

Turbo forms has lots of unhelpful side effects. We currently disable it on a per-form basis, but as there's no form where we _do_ want it, it's easier to disable it globally.

ACD-280: Disable turbo-forms

---

app/assets/javascript/application.js

I turned off Turbo Forms to stop form submissions being intercepted (and occasionally broken) by Turbo. BUT in doing so I turned off Turbo's "sneakily turn this link into a button" functionality, which is how sign-out and delete-user links work.
By switching the mode to "opt-in", Turbo won't kick in unless it's explicitly asked via thing like the `turbo_method` annotation. That way it won't interfere with forms, but it will do "sneakily turn this link into a button".

Allow explicit use of turbo

---

app/assets/stylesheets/components/_summary.scss
app/views/users/index.html.haml
config/application.rb
config/locales/en/views/users.yml

- date wrap in single line
- the date show the year now
- wider table
- it show inactive users (> 3 months inactivity)
- it show users that have never logged-in

Improvements for List of users Page.

---

app/controllers/subjects_controller.rb
lib/court_data_adaptor/query/unlink_court_application.rb
spec/features/unlink_court_applications_spec.rb
spec/fixtures/vcr_cassettes/spec/features/unlink_court_applications_successfully_spec.yml

As a defence against weird situations where the CDA database ends up with multiple LaaReference records for the same subject ID with different MAAT references, when unlinking court applications, pass in the MAAT reference we want to unlink _from_. (We already do this for prosecution cases).

ACD-368: Add MAAT reference when unlinking court applications

---

app/controllers/searches_controller.rb
app/models/cda/defendant.rb
app/models/cda/laa_application.rb
app/models/cda/offence_summary.rb
app/views/searches/_results.html.haml

On the search results screen we don't have proper code checking if a defendant is linked or not - we always return nil. By wrapping the defendant in a decorator that has a proper `linked?` method, and granting access to the offence_summary->laa_application attributes as objects, we can use our existing "is this linked?" logic.

Bug linked link

---

app/controllers/application_controller.rb
app/controllers/defendants_controller.rb
app/controllers/hearings_controller.rb
app/controllers/laa_references_controller.rb
app/controllers/prosecution_cases_controller.rb
app/controllers/searches_controller.rb
app/controllers/subjects_controller.rb
config/i18n-tasks.yml
config/locales/en/cda_errors.yml
config/locales/en/views/error.yml
lib/court_data_adaptor/errors.rb
spec/features/defendants_view_spec.rb
spec/features/search/cda/case_reference_spec.rb
spec/requests/linking/link_defendant_maat_reference_v2_spec.rb
spec/support/webmock/court_data_adaptor/webmock.rb

When CDA returns a failure response, try to extract an error code from the body, and if one is found and we know a user-friendly string that is appropriate to it, display that string in the UI.
[Link to story](https://dsdmoj.atlassian.net/browse/ACD-806)

ACD-806: Show error codes

---

app/views/defendants/_form.html.haml
config/locales/en/views/defendants.yml

Bring defendant unlinking inline with defendant linking and appellant linking/unlinking by auto-disabling the submit button on click.
https://dsdmoj.atlassian.net/browse/ACD-831

ACD-831: Prevent double-click

---

app/controllers/defendants_controller.rb

Fix undefined method 'errors'.
The JsonApiClient::Errors::NotFound will be rescued by `StandardError`. It does not contain the method errors, hence it cannot be handled by `handle_error`.

Fix undefined method 'errors'.

---

app/controllers/defendants_controller.rb
app/views/defendants/_form.html.haml
app/views/laa_references/_form.html.haml
app/views/layouts/application.html.haml
app/views/search_filters/_form.html.haml
app/views/searches/_form.html.haml
app/views/subjects/show.html.haml
app/views/users/_form.html.haml

Makes Error Summary consistent with all the form: according with the GDS guide (https://design-system.service.gov.uk/components/error-summary/) the Error Summary component must stay "at the top of a page" and not under the page header.
https://dsdmoj.atlassian.net/browse/ACD-839

Acd 839 consistent error summary for all the forms

---

app/controllers/defendants_controller.rb
spec/features/unlinking_a_defendant_from_maat_spec.rb
spec/requests/unlinking/unlink_defendant_maat_reference_v2_spec.rb

When users click 'Create link without a MAAT ID', a dummy MAAT ID gets generated that starts with an `A`. When we try to unlink, we need to pass the current MAAT ID to CDA, but `to_i` turns the dummy MAAT ID to a 0. MAAT IDs are strings, not numbers (because they can contain A or Z) so should be treated as such.

ACD-863: Cope with maat references that start with A

---

app/controllers/concerns/breadcrumbs.rb
app/controllers/court_applications_controller.rb
app/controllers/hearing_days_controller.rb
app/controllers/subjects_controller.rb
app/views/maintenance_mode/show.html.haml
config/locales/en/views/searches.yml
config/locales/en/views/subjects.yml
spec/features/application_subjects_spec.rb

Breadcrumbs are shorter and mirror logical structure of the site:
```
Home:
Search:
Case:
Defendant
Hearing
Appeal:
Appellant
Hearing day
```

ACD-853: Standardise breadcrumbs

---

app/assets/javascript/application.js
app/controllers/users_controller.rb
app/models/user_search.rb
app/services/user_search_service.rb
app/views/users/_search_form.html.haml
app/views/users/index.html.haml
config/locales/en/views/users.yml
config/routes.rb
spec/features/users/index_users_spec.rb
spec/services/user_search_service_spec.rb

https://dsdmoj.atlassian.net/browse/ACD-855
Use the MoJ filter component to do a basic search by name, username, email and last sign in date in a way that's compatible with pagination but doesn't put caseworker PII in the query string.

ACD-855: search users

---

app/models/cda/base_model.rb
app/models/cda/defendant.rb
app/models/cda/hearing_event_log.rb
app/models/cda/offence_history_collection.rb
spec/models/cda/defendant_spec.rb

VCD is breaking when the URN has a space in it, but escaping is also important to prevent malicious requests being passed on to CDA

ACD-890: Sanitise URL params we pass on to CDA

---

app/assets/stylesheets/components/_phase_banner.scss
app/views/search_filters/_form.html.haml
spec/features/search/cda/case_reference_spec.rb
spec/features/search/cda/defendant_by_name_spec.rb
spec/features/search/cda/defendant_by_reference_spec.rb
spec/features/search/cda/filters_spec.rb
spec/features/search/filters_spec.rb
spec/features/sign_in_spec.rb
spec/features/users/edit_user_spec.rb
spec/features/users/index_users_spec.rb
spec/features/users/password_change_spec.rb
spec/features/users/password_reset_spec.rb
spec/features/users/password_unlock_spec.rb

Our current accessibility checks just check #main. This PR expands the checks to check the whole page, and fixes the issues raised:
- The root search screen is lacking an h1 - fixed by inserting one into the form legend
- The 'local' tag is not sufficiently high contrast - fixed by changing the text color in the label

ACD-278: Expand accessibility checks to cover whole page
