.circleci/config.yml, .codeclimate.yml, Gemfile, Gemfile.lock, README.md
Add simplecov and codeclimate
https://dsdmoj.atlassian.net/browse/CACP-163
To support code quality
=> Add codeclimate

.env.development, .env.test, .k8s/dev/deployment.yaml, app/views/layouts/_google_analytics.html.haml, app/views/layouts/application.html.haml, spec/features/layout_spec.rb, spec/requests/root_spec.rb
Add monitoring to the service using Google Analytics
[Add google analytics](https://dsdmoj.atlassian.net/browse/CACP-182)
To enable web analytics for the service.
=> [CACP-182] Add Google analytics

app/helpers/govuk_design_system_helper.rb, spec/helpers/govuk_design_system_helper_spec.rb
Add service name to page title
[Add service name to page title](https://dsdmoj.atlassian.net/browse/CACP-181)
Accessibility and best practice update to the application.
=> [CACP-181] Add service name to page title

package.json, yarn.lock
Fix npm sub dependency
Github security alert identified vulnerability in a dependency.
=> fix minimist security alert

config/locales/en/views/searches.yml
Tweak search filter content
In line with other filter descrptions.
Also need to confirm whether to change the filters
content more generally inline with designs
=> Amend case reference content

config/webpacker.yml
Stop checking development yarn integrity error
prevents rails running
=> Stop checking development yarn integrity error

lib/court_data_adaptor/query/prosecution_case.rb, spec/fixtures/vcr_cassettes/spec/features/search/case_reference_spec.yml, spec/lib/court_data_adaptor/query/prosecution_case_spec.rb
parse search term to apply expected URN formatting
So user input is parsed to expected URN format
basic passing of user input to remove
hyphens, forward-slashes, whitespace and
case.
=> Apply basic parsing of case URNs as part of search

app/controllers/help_controller.rb, app/views/help/cookies.html.haml, app/views/layouts/_cookie_banner.html.haml, app/views/layouts/_footer.html.haml, app/views/layouts/_google_analytics.html.haml, app/views/layouts/application.html.haml, app/webpack/javascripts/analytics.js, app/webpack/javascripts/cookie-banner.js, app/webpack/javascripts/cookie-helper.js, app/webpack/packs/application.js, app/webpack/stylesheets/application.scss, app/webpack/stylesheets/components/_cookie_banner.scss, config/locales/en/views/cookies.yml, config/locales/en/views/layouts.yml, config/routes.rb, package.json, spec/features/help/cookies_spec.rb, spec/features/layout_spec.rb, spec/requests/root_spec.rb, yarn.lock
Implement cookie policy functionality.
[CACP-247 Implement cookie policy functionality](https://dsdmoj.atlassian.net/browse/CACP-247)
Adherence with The Privacy and Electronic Communications Regulations (PECR).
=> Add cookie policy

Gemfile, Gemfile.lock, app/controllers/feedback_controller.rb, app/mailers/feedback_mailer.rb, app/models/feedback.rb, app/views/feedback/_form.html.haml, app/views/feedback/new.html.haml, app/views/layouts/_phase_banner.html.haml, config/application.rb, config/locales/en/models/feedback.yml, config/locales/en/views/feedback.yml, config/locales/en/views/layouts.yml, config/routes.rb, spec/features/feedback_spec.rb, spec/mailers/feedback_mailer_spec.rb, spec/models/feedback_spec.rb, spec/rails_helper.rb, spec/requests/feedback_spec.rb
Add mechanism for users to submit feedback
https://dsdmoj.atlassian.net/browse/CBO-1267
To improve service
By clicking on the feedback link users can submit their feedback (a rating plus a comment, and optionally their email address) to a support email address.
=> Add feedback mechanism

app/controllers/feedback_controller.rb
Feedback email was failing when testing locally because environment was nil.
N/A
To enable local testing of feedback mechanism
Use Rails.env as fallback where ENV = nil
=> Fix feedback environment not populated

db/migrate/20200619115713_change_username_null_on_users.rb, db/schema.rb
enforce presence of username at DB level
Username is required for ulinking, at least
Apply via migration with defaults and
applies a unique username
=> Change DB user:username `null: false`

config/initializers/sidekiq.rb, docs/development.md
Activate sidekiq enqueuing and performing
of jobs as in test environment
This enables jobs to be performed synchronously by sidekiq,
enabling enqueuing and processing.
It also means jobs are output in the console where details can be
viewed/checked.
Add sidekiq initializer that enables testing mode in
development
=> Run sidekiq inline in development

app/views/defendants/show.html.haml, app/views/prosecution_cases/show.html.haml, config/locales/en/generic.yml, spec/features/unlinked_defendant_flow_spec.rb
Add heading caption to relevant views
[Add caption to headings](https://dsdmoj.atlassian.net/browse/CBO-1330)
Make heading more descriptive and follows the designs.
=> Add case and defendant heading caption

app/helpers/govuk_design_system_helper.rb, spec/helpers/govuk_design_system_helper_spec.rb, spec/support/capybara_extensions.rb
Fix html tag, tag should be `<details>` instead of `<detail>`
=> Minor fix to details component

spec/helpers/defendant_helper_spec.rb
Add missing defendant_helper_spec.rb
n/a
This was missing in error from https://github.com/ministryofjustice/laa-court-data-ui/pull/216
Added spec/helpers/defendant_helper_spec.rb
=> Add missing defendant_helper_spec.rb

app/models/unlink_attempt.rb, app/views/defendants/_form.html.haml, app/views/laa_references/_form.html.haml, config/locales/en/models/unlink_attempt.yml, spec/requests/linking/unlink_defendant_maat_reference_spec.rb
Resolve bugs identified during testing
=> Multi bug fixes

.circleci/build.sh, .k8s/scripts/build.sh
Change ECR login mechanism to use get-login-password and --password-stdin
More secure and old get-login mechanism is deprecated
=> Change ECR login mechanism

app/webpack/packs/unlink.js
Sonarqube issue - "Unnecessary semicolon"
[CBO-1469: Resolve Sonarqube FrontEnd issues](https://dsdmoj.atlassian.net/browse/CBO-1469)
Non-compliant code
=> Remove unnecessary semicolon in JS

app/models/user.rb, spec/models/user_spec.rb
Spec devise mailer backgrounding overide
should have been spec'd
=> Spec devise mailer backgrounding overide

.circleci/config.yml, .circleci/deploy.sh, .k8s/scripts/deploy.sh
Fail deployment overtly if "pods" do not reach "readiness"
[CBO-1556](https://dsdmoj.atlassian.net/browse/CBO-1556)
Currently deployment is green as long as the Kubernetes apply
commands are successful, but the pods may still fail to start
the application up and various other scenarios could prevent
the deployment actually succeeding.
depends on this [CP PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/3431) being merged and applied
=> Show error in CI pipeline when deployment fails

.circleci/build.sh, .circleci/config.yml, .circleci/deploy.sh
Use cloud platforms latest tools image
The old tools:circleci image is out of date
(client 1.11.x) and no longer supported.
=> Use cloud platforms latest tools image

.k8s/production/deployment-worker.yaml
=> Fix production worker namespace

README.md
They are not displaying for some reason
=> Remove codescene badges

.github/workflows/codeql-analysis.yml
Add codeql-analysis.yml config for github action
n/a
Improve security analysis
Use new [github code scanning actions](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/enabling-code-scanning-for-a-repository#enabling-code-scanning-using-actions)
=> Create github action for javascript security analysis 

.circleci/config.yml, .git-hooks/pre-commit, .stylelintrc.yml, Makefile, app/webpack/stylesheets/application.scss, app/webpack/stylesheets/components/_cookie_banner.scss, docs/testing.md, package.json, yarn.lock
Update JS & SCSS linting
[Update JS & SCSS linting](https://dsdmoj.atlassian.net/browse/CBO-1636)
To enforce consistent linting tooling & strategy
=> Update JS & SCSS linting

app/views/devise/mailer/confirmation_instructions.html.haml, app/views/devise/mailer/reset_password_instructions.html.haml, app/views/devise/mailer/unlock_instructions.html.haml, app/views/devise/shared/_links.html.haml, app/views/results/_defendant.html.haml, app/views/results/_prosecution_case.html.haml
Add missing govuk-link class to links without it
n/a
Noticed there were some missing links. I believe the
the devise mailers are not used to it should not matter
but have amended for completeness.
=> Add missing govuk-link class to links without it

.codeclimate.yml
Inline with gem version in app
=> Bump codeclimate rubocop 0-90 --> 1-9-1

app/models/search.rb, app/validators/char_length_validator.rb, app/validators/visible_length_validator.rb, config/locales/en/models/search.yml, lib/court_data_adaptor/query/defendant/by_name.rb, spec/features/search/case_reference_spec.rb, spec/features/search/defendant_by_name_spec.rb, spec/fixtures/vcr_cassettes/spec/features/search/defendant_by_name_spec.yml, spec/fixtures/vcr_cassettes/spec/lib/court_data_adaptor/query/defendant/by_name_spec.yml, spec/fixtures/vcr_cassettes/spec/requests/search/defendant_by_name_spec.yml, spec/lib/court_data_adaptor/query/defendant/by_name_spec.rb, spec/models/search_spec.rb, spec/requests/search/defendant_by_name_spec.rb, spec/support/matchers/have_activerecord_error.rb
Partial name search
[CBO-1756](https://dsdmoj.atlassian.net/browse/CBO-1756)
Enable case workers to search for defendants using
partial name matching.
Pass search term direct to adaptor and do not
filter response/results.
Since common platform will search
by name case-insensitively and apply
partial matching VCD and CDA do not
need to manipulate the search term
nor the results returned.
=> [CBO-1756] partial name search

app/views/hearings/_hearing_events.html.haml, lib/court_data_adaptor/resource/hearing_event.rb, spec/lib/court_data_adaptor/resource/hearing_event_spec.rb, spec/views/hearings/_hearing_events.html.haml_spec.rb
Reverts ministryofjustice/laa-court-data-ui#570
=> Revert "[AAC-62] Display event hearing notes"

app/controllers/users_controller.rb, app/views/users/export.csv.erb, app/views/users/index.html.haml, config/locales/en/views/users.yml, config/routes.rb, spec/features/users/index_users_spec.rb, spec/requests/users/manager_spec.rb
Add last signed in data to the users table and ability to export the table information
[AAC-465](https://dsdmoj.atlassian.net/browse/AAC-465)
Security Requirement
Expose data from the database we already keep for last signed in. Output data into CSV and output to new endpoint
=> AAC-465 - Add last sign in and export functionality

.k8s/live/staging/deployment.yaml, .k8s/live/uat/deployment.yaml
Enable MAAT linking and unlinking in pre-production for testing prior to release
[CDUI - Enable MAAT Linking/ Unlinking in V2](https://dsdmoj.atlassian.net/browse/AAC-584)
V2 Migration
Add LAA_REFERENCES env var as true on deployment.yaml in uat and stage
=> AAC-584 - Enable MAAT linking/unlinking in uat/staging

.k8s/live/dev/ingress.yaml, .k8s/live/production/ingress.yaml, .k8s/live/staging/ingress.yaml, .k8s/live/uat/ingress.yaml
=> AAC-623 - Block script IP

config/application.rb, config/initializers/devise.rb, docker/Dockerfile
Update Email Address from Laa-Get-Paid to assessaclaim
[Change Court Data Feedback form recipient ](https://dsdmoj.atlassian.net/browse/AAC-624)
Ensure that the correct people are notified when requests come through
=> AAC-624 - Update email address

.k8s/live/dev/deployment.yaml
Set HEARING env variable to true in the Dev environment
[AAC-628](https://dsdmoj.atlassian.net/browse/AAC-628)
V2 Migration
Set the V2 environment variable `HEARING` to true
`HEARING: true`
=> AAC-628 Enable V2 Hearing Day page in DEV environment

.k8s/live/production/deployment.yaml
Revert flag after finding issue on hearing page
=> change flag to false

.git-crypt/keys/default/0/A61E7D53338E74DD8C4423DB3EFFAE40C9E32BC7.gpg
New collaborators:
C9E32BC7 Sam Kyprianou <samuel.kyprianou@digital.justice.gov.uk>
=> AAC-723 - Add 1 git-crypt collaborator

.haml-lint_todo.yml, app/views/layouts/_flashes.html.haml, app/views/pages/contact_us.html.haml
[AAC-710 Fix HAML Linting Issues: TrailingWhitespace](https://dsdmoj.atlassian.net/browse/AAC-710)
Fixed linting issues for TrailingWhitespace in HAML file
=> Aac 710/haml linting trailing whitespace

Gemfile, Gemfile.lock, package.json, yarn.lock
Merge the following dependabot PRs together:
* #1308
* #1309 
* #1310 
* #1311
[Release of dependency and security patches (Sprint - Ewan's Angels)](https://dsdmoj.atlassian.net/browse/CTSKF-145)
Avoid multiple CircleCI runs as dependabot rebases each PR after every merge.
Cherry-pick all the commits into one branch.
=> Dependabot updates on 21/12/22

Gemfile, Gemfile.lock
Merge Depednabot updates.
[Release of dependency and security patches (Sprint - Famous Five)](https://dsdmoj.atlassian.net/browse/CTSKF-159)
Combine the commits from the following PRs:
* #1314 
* #1315 
* #1316 
* #1317 
* #1318 
* #1319 
All of these are testing libraries with the exception of `net-imap` and the only update in `net-imap` reverts a testing related change in the previous version.
=> [CTSKF-159] Dependabot updates for 28/12/22

docs/development.md
Refer to Confluence document on secret strategy instead of explicitly stating in Readme 
[Ticket](https://dsdmoj.atlassian.net/browse/CTSKF-178)
We may be exposing ourselves to exploits if we show too much about where we put our secrets in public domain
=> Update development.md to be more vague about secrets

Gemfile, Gemfile.lock, package.json, yarn.lock
Applying the following dependabot updates:
* #1335
* #1336 
* #1337 
* #1338 
* #1342 
* #1346
=> Dependabot updates on 11/01/23

Gemfile, Gemfile.lock, package.json, yarn.lock
Dependabot updates:
* #1360 
* #1361 
* #1362 
* #1363 
* #1365 
* #1366 
* #1367 
* #1368
=> Dependabot 230201

Gemfile.lock, package.json, yarn.lock
Dependabot updates:
* #1429 
* #1430 
* #1432
* #1433 
* #1435 
* #1437
=> Dependabot updates

package.json, yarn.lock
Combines All Node Updates pending via dependabot
[Release of dependency and security patches (Sprint - N)](https://dsdmoj.atlassian.net/browse/CTSKF-346)
To ensure our applications are secure, supported and up to date
Combine all the changes to package.json to one commit then run yarn install
=> 17/04/2023 - Node module updates (dependabot)

app/decorators/offence_summary_decorator.rb, spec/fixtures/stubs/cd_api/defendants_body.json
Fix the decorator to use the pleas array rather than the initial object when we were implementing this. 
N/A
=> Fix decorator to use pleas array

Gemfile.lock, package.json, yarn.lock
Grouped together dependabot updates for: 
https://github.com/ministryofjustice/laa-court-data-ui/pull/1514
https://github.com/ministryofjustice/laa-court-data-ui/pull/1513
https://github.com/ministryofjustice/laa-court-data-ui/pull/1509
https://github.com/ministryofjustice/laa-court-data-ui/pull/1508
https://github.com/ministryofjustice/laa-court-data-ui/pull/1506
https://github.com/ministryofjustice/laa-court-data-ui/pull/1502
[Release of dependency and security updates - Sprint Q](https://dsdmoj.atlassian.net/browse/CTSKF-418)
Keep site secure, updated and maintainable 
Note: not all dependabot updates are in because some need manual changes
Merge dependabot  branches
=> 20230525 dependabot updates

package.json, yarn.lock
Dependabot updates:
* #1541 
* #1542
* #1543 
* #1544
=> Dependabot 20230608

.github/workflows/codeql-analysis.yml, Gemfile.lock, package.json, yarn.lock
Dependabot updates;
* #1673 
* #1674 
* #1675 
* #1676
=> Dependabot 230905

Gemfile.lock, package.json, yarn.lock
Dependabot update;
* #1677
* #1681
=> Dependabot 230906

.circleci/config.yml
Upgrade CircleCI orb called browser-tools
[CTSKF-615](https://dsdmoj.atlassian.net/browse/CTSKF-615)
[CTSKF-615]: https://dsdmoj.atlassian.net/browse/CTSKF-615?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> CTSKF-615 Upgrade circleci orb called browser-tools

Gemfile, Gemfile.lock, package.json, yarn.lock
Group Ruby and Javascript Dependabot minor and patch updates
[Release of dependency and security updates - Sprint][(link](https://dsdmoj.atlassian.net/browse/CTSKF-685))
Grouping the Dependabot saves a lot of time testing and deploying.
https://github.com/ministryofjustice/laa-court-data-ui/pull/1891
https://github.com/ministryofjustice/laa-court-data-ui/pull/1890
https://github.com/ministryofjustice/laa-court-data-ui/pull/1888
https://github.com/ministryofjustice/laa-court-data-ui/pull/1886
https://github.com/ministryofjustice/laa-court-data-ui/pull/1884
https://github.com/ministryofjustice/laa-court-data-ui/pull/1883
--------
=> Ctskf 685 dependabot pr cd UI

.github/workflows/codeql-analysis.yml, package.json, yarn.lock
Group Ruby and Javascript Dependabot minor and patch updates
[Release of dependency and security updates - Sprint](https://dsdmoj.atlassian.net/browse/CTSKF-685)
Grouping the Dependabot saves a lot of time testing and deploying.
https://github.com/ministryofjustice/laa-court-data-ui/pull/1879
https://github.com/ministryofjustice/laa-court-data-ui/pull/1877
https://github.com/ministryofjustice/laa-court-data-ui/pull/1876
https://github.com/ministryofjustice/laa-court-data-ui/pull/1874
https://github.com/ministryofjustice/laa-court-data-ui/pull/1825
https://github.com/ministryofjustice/laa-court-data-ui/pull/1756
--------
=> Ctskf 685 dependabot pr cd UI two

Gemfile, Gemfile.lock, package.json, yarn.lock
Update dependencies by grouping Dependabot updates in order to keep our app up to date with security fixes/patches and feature updates so that it continues to run successfully, accurately and securely.
#### List of dependabot PRs
https://github.com/ministryofjustice/laa-court-data-ui/pull/1904
https://github.com/ministryofjustice/laa-court-data-ui/pull/1905
https://github.com/ministryofjustice/laa-court-data-ui/pull/1908
https://github.com/ministryofjustice/laa-court-data-ui/pull/1909
=> Dependabot updates 20240209

package.json, yarn.lock
Grouping of Javascript dependabot PRs:
https://github.com/ministryofjustice/laa-court-data-ui/pull/1933
https://github.com/ministryofjustice/laa-court-data-ui/pull/1945
https://github.com/ministryofjustice/laa-court-data-ui/pull/1948
https://github.com/ministryofjustice/laa-court-data-ui/pull/1949
https://github.com/ministryofjustice/laa-court-data-ui/pull/1950
=> Dependency updates 20240307

Gemfile, Gemfile.lock, package.json, yarn.lock
Combines the following dependabot updates:
https://github.com/ministryofjustice/laa-court-data-ui/pull/2070
https://github.com/ministryofjustice/laa-court-data-ui/pull/2079
https://github.com/ministryofjustice/laa-court-data-ui/pull/2081
https://github.com/ministryofjustice/laa-court-data-ui/pull/2083
https://github.com/ministryofjustice/laa-court-data-ui/pull/2086
https://github.com/ministryofjustice/laa-court-data-ui/pull/2088
=> Dependency updates 10/06/2024

package.json, yarn.lock
Javascript dependabot updates:
* #2186 
* #2206 
* #2207 
* #2208 
* #2209 
* #2211 
* #2214
=> Dependabot 240903 js

yarn.lock
Dependabot (javascript)
* #2210 
* #2212 
* #2213 
* #2215 
* #2216
=> Dependabot 240903

yarn.lock
Dependabot (javascript):
* #2221 
* #2222 
* #2223 
* #2224 
* #2225 
* #2226 
* #2227 
* #2228 
* #2229 
* #2230 
* #2231 
* #2232
=> Dependabot 240904

Gemfile.lock, yarn.lock
Dependabot:
* #2257 
* #2258 
* #2259 
* #2260 
* #2261 
* #2262 
* #2263 
* #2264 
* #2265 
* #2266 
* #2267
* #2223 
* #2256
=> Dependabot 240906

Gemfile, Gemfile.lock, package.json, yarn.lock
Dependabot:
* #2269 
* #2270 
* #2271 
* #2272 
* #2273 
* #2274 
* #2275 
* #2276 
* #2277 
* #2278 
* #2279 
* #2280 
* #2281 
* #2283 
* #2284 
* #2285 
* #2286
=> Dependabot 240909

Gemfile, Gemfile.lock, yarn.lock
Dependabot:
* #2288 
* #2289 
* #2290 
* #2291 
* #2292 
* #2293 
* #2294 
* #2295 
* #2296 
* #2297 
* #2298 
* #2299 
* #2300 
* #2301
=> Dependabot 240910

package.json, yarn.lock
Dependabot:
* #2303 
* #2304 
* #2305 
* #2306 
* #2307 
* #2308 
* #2309 
* #2310 
* #2311 
* #2312 
* #2313 
* #2314
=> Dependabot 240911

yarn.lock
Dependabot:
* #2316 
* #2317 
* #2318 
* #2319 
* #2320 
* #2321 
* #2322 
* #2323 
* #2324 
* #2325 
* #2326 
* #2327
=> Dependabot 240912

Gemfile, Gemfile.lock, package.json, yarn.lock
Dependabot:
* #2329 
* #2330 
* #2331 
* #2332 
* #2333 
* #2334
* #2335 
* #2336 
* #2337 
* #2338 
* #2339 
* #2340 
* #2341
=> Dependabot 240913

Gemfile.lock, yarn.lock
Dependabot:
* #2343 
* #2344 
* #2345 
* #2346 
* #2347 
* #2348 
* #2349 
* #2350 
* #2351 
* #2352 
* #2353 
* #2354 
* #2355 
* #2356 
* #2357
=> Dependabot 240916

Gemfile.lock, yarn.lock
Dependabot:
* #2412 
* #2413 
* #2429 
* #2430 
* #2432 
* #2433 
* #2435 
* #2437 
* #2438
=> Dependabot 240924

package.json, yarn.lock
Combines dependabot PRs for Javascript dependencies
=> Javascript Dependabot updates 2024-11-04

package.json, yarn.lock
Combines dependabot PRs for Javascript dependencies
=> Javascript Dependabot updates 2024-11-07

Gemfile.lock, package.json, yarn.lock
Groups dependabot PRs for ease of release.
=> Dependabot updates - 2024-11-08

package.json, yarn.lock
Groups dependabot updates to javascript dependencies
=> Javascript dependencies 2024-11-14

Gemfile.lock, package.json, yarn.lock
Groups dependabot updates for ruby and javascript dependencies.
=> Dependency updates 2024-11-19

.k8s/live/staging/deployment-worker.yaml, .k8s/live/staging/deployment.yaml
Note that this will need some secrets updating to accompanying, but that's not done via PR
=> ACD-623: Staging should point to CDA test

app/controllers/hearing_days_controller.rb, app/controllers/subjects_controller.rb, app/decorators/cd_api/hearing_decorator.rb, app/services/cd_api/hearing_details/defence_counsels_list_service.rb, app/services/court_data_adaptor/court_application_result_string_service.rb, app/views/court_applications/show.html.haml, app/views/hearing_days/show.html.haml, app/views/hearings/_attendees_v2.html.haml, app/views/layouts/application.html.haml, app/views/subjects/show.html.haml, config/i18n-tasks.yml, config/locales/en/views/court_applications.yml, config/locales/en/views/hearing_days.yml, config/locales/en/views/subjects.yml, config/routes.rb, lib/court_data_adaptor/resource/application_hearing.rb, lib/court_data_adaptor/resource/application_summary.rb, lib/court_data_adaptor/resource/court_centre.rb, lib/court_data_adaptor/resource/hearing_day.rb, lib/court_data_adaptor/resource/offence_summary.rb, lib/court_data_adaptor/resource/plea_summary.rb, spec/decorators/cd_api/hearing_decorator_spec.rb, spec/features/application_hearings_spec.rb, spec/features/application_subjects_spec.rb, spec/features/court_applications_spec.rb, spec/fixtures/vcr_cassettes/spec/features/application_hearings_spec.yml, spec/fixtures/vcr_cassettes/spec/features/application_subjects_spec.yml, spec/services/cd_api/hearing_details/defence_counsels_list_service_spec.rb, spec/services/court_data_adaptor/court_application_result_string_service_spec.rb
New page for details of the subject of a court application
[As a caseworker I want to be able to access the defendant page](https://dsdmoj.atlassian.net/browse/ACD-529)
[As a caseworker I want to see a defendant summary](https://dsdmoj.atlassian.net/browse/ACD-531)
[As a caseworker I want to see an offence summary](https://dsdmoj.atlassian.net/browse/ACD-530)
=> ACD-529, 530, 531, 539, 540, 541, 567 & 569: Appeal subject and hearings pages, and appeal result

app/controllers/subjects_controller.rb, app/models/court_application_link_status.rb, app/models/unlink_attempt.rb, app/views/subjects/show.html.haml, config/locales/en/models/link_attempt.yml, config/locales/en/views/subjects.yml, config/routes.rb, lib/court_data_adaptor/query/link_court_application.rb, lib/court_data_adaptor/query/unlink_court_application.rb, lib/court_data_adaptor/resource/subject_summary.rb, spec/features/link_court_applications_spec.rb, spec/features/unlink_court_applications_spec.rb, spec/fixtures/vcr_cassettes/spec/features/link_court_applications_successfully_spec.yml, spec/fixtures/vcr_cassettes/spec/features/link_court_applications_unsuccessfully_spec.yml, spec/fixtures/vcr_cassettes/spec/features/unlink_court_applications_successfully_spec.yml, spec/fixtures/vcr_cassettes/spec/features/unlink_court_applications_unsuccessfully_spec.yml, spec/models/link_attempt_spec.rb, spec/requests/linking/link_defendant_maat_reference_v2_spec.rb
Add a simple form to link a MAAT ID to a court application if it's not linked already
[As a case worker, I want to link the appeal application to a MAAT ID so that I can see further hearing and outcome data within VCD and the wider LAA estate](https://dsdmoj.atlassian.net/browse/ACD-533)
=> ACD-533 & 535: Link and unlink MAAT ID to and from appeals

app/views/defendants/_form.html.haml, app/views/defendants/edit.html.haml, app/views/laa_references/_form.html.haml, app/views/laa_references/new.html.haml, app/views/prosecution_cases/show.html.haml
Make some tables full width (while keeping some parts of pages two-thirds width)
=> ACD-676: Make tables wider

config/locales/en/views/court_applications.yml, config/locales/en/views/hearing_days.yml, config/locales/en/views/subjects.yml, spec/features/application_hearings_spec.rb, spec/features/application_subjects_spec.rb
Change some wordings based on feedback
=> ACDs-681, 682, 683, 684: Tweak wordings

app/controllers/hearing_days_controller.rb, app/controllers/hearings_controller.rb, app/decorators/cd_api/hearing_decorator.rb, app/models/cda/base_model.rb, app/models/cda/hearing_event_log.rb, spec/features/hearings_spec.rb, spec/fixtures/vcr_cassettes/spec/features/application_hearings_spec.yml, spec/fixtures/vcr_cassettes/spec/features/hearing_pagination_spec.yml, spec/support/webmock/court_data_api/webmock.rb, spec/views/hearings/_hearing_events.html.haml_spec.rb, spec/views/hearings/show.html.haml_spec.rb
As a step towards retiring CDAPI
[[Discontinue CDAPI] Retire GET /v2/hearings/<uuid>/hearing_events](https://dsdmoj.atlassian.net/browse/ACD-678)
=> ACD-678: Load hearing events directly from CDA

.rubocop.yml, app/controllers/hearings_controller.rb, app/controllers/laa_references_controller.rb, app/models/cda/base_model.rb, app/models/cda/hearing.rb, config/application.rb, spec/features/breadcrumbs_spec.rb, spec/features/hearing_pagination_spec.rb, spec/features/hearings_spec.rb, spec/fixtures/stubs/cda/internal_v2_hearing_results_response.json, spec/fixtures/vcr_cassettes/spec/features/hearing_pagination_spec.yml, spec/requests/hearings_spec.rb, spec/support/webmock/court_data_adaptor/webmock.rb
retire cda v2 hearings
Acd-673
=> Acd-673 retire cda v2 hearings

app/views/defendants/_form.html.haml, app/views/laa_references/_form.html.haml, app/views/subjects/show.html.haml, helm_deploy/templates/deployment.yaml, helm_deploy/values/dev.yaml, helm_deploy/values/production.yaml, helm_deploy/values/staging.yaml, helm_deploy/values/uat.yaml, spec/features/defendants_view_spec.rb, spec/features/link_court_applications_spec.rb
In case we need to bring VCD online before MAAT is ready
=> Feature flag to disable linking/unlinking functionality in UI

helm_deploy/values/production.yaml, helm_deploy/values/uat.yaml
Disable the display of Link/Unlink in UI (noLinking: true)
=> Disable of Link/Unlink in UAT and Prod

helm_deploy/templates/ingress.yaml
[board ticket description](link)
--------
=> Whitelisting IPs

app/controllers/subjects_controller.rb, spec/features/application_subjects_spec.rb
Make sure the last breadcrumb is added after the first ones.
=> ACD-801: Fix breadcrumb ordering bug

app/controllers/stats_controller.rb
Disable StatsController#show based on the FeatureFlag show_stats
=> Disable StatsController#show based on the FeatureFlag show_stats
